// ==========================================================================
// Diccionario DCI → subgrupo ATC (nivel 2), DERIVADO DE FUENTE VERIFICABLE.
//
// Fuente: INVIMA — Código Único de Medicamentos Vigentes (CUM), datos abiertos
//   datos.gov.co dataset i7cb-raxc. Export descargado 2026-07-22 (157.789 filas).
// Generado por scripts/gen_atc_lookup.py (reproducible). NO EDITAR A MANO.
//   1. Por fila se extrae el principio activo CANÓNICO del texto ruidoso.
//   2. Por ingrediente se toma el ATC de producto de UN SOLO principio activo
//      (descarta el combinado vía la descripción ATC) y su moda; p. ej.
//      hidroclorotiazida → C03 (su clase), no C09 (combo).
//   3. Se guarda el subgrupo ATC nivel 2 (3 caracteres); nivel 1 = 1ª letra.
//
// Las correcciones por sesgo de combinado / vacíos del CUM viven, anotadas con
// su ATC oficial, en atc.ts.
// ==========================================================================

export const ATC_LEVEL2_BY_INGREDIENT: Readonly<Record<string, string>> = Object.freeze({
  '* acetaminofen': 'N02',
  '*aztreonam polvo esteril masarginina * aztreonampara inyeccion es una mezcla seca esteril aztreonam argininasegun': 'J01',
  '*etinilestradiol': 'G03',
  '*icosapentanoato etilo * cantidad dispensar depende potencia principio activo potencia teorica icosapentanoato etilo': 'C10',
  '*paracetamol compresion directa': 'N02',
  '*proteina': 'B02',
  '*simeticona *': 'A02',
  '*tiocolchicosido': 'M01',
  'abacavir': 'J05',
  'abacavir equivalentea abacavir': 'J05',
  'abatacept': 'L04',
  'abemaciclib': 'L01',
  'abiraterona': 'L02',
  'abiraterona acetona': 'L01',
  'abrocitinib': 'D11',
  'acalabrutinib': 'L01',
  'acebrofilina': 'R05',
  'aceclofenac': 'M01',
  'aceclofenaco': 'M01',
  'aceite eucalipto': 'C01',
  'aceite eucaliptol': 'M02',
  'aceite eucaliptus': 'R01',
  'aceite higado bacalao vitamina vitamina d que aportan vitamina vitamina d': 'A11',
  'aceite mineral': 'N01',
  'aceite oliva refinado': 'B05',
  'aceite oliva refinado aceite soya refinado': 'B05',
  'aceite pescado': 'B05',
  'aceite pescado altamente refinado acido eicosapentanoico acido docosahexanoico dl alfa tocoferol': 'B05',
  'aceite pescado rico acidos omega': 'B05',
  'aceite pescado rico omega acidos conteniendo acido eicosapentaenoico': 'A11',
  'aceite ricino': 'A06',
  'aceite soja': 'B05',
  'aceite soja refibado': 'B05',
  'aceite soya': 'B05',
  'aceite soya lct': 'B05',
  'aceite soya purificado': 'B05',
  'aceite soya refinado': 'B05',
  'aceponato hidrocortisona': 'D07',
  'aceponato metilprednisolona': 'D07',
  'acetaminofem': 'N02',
  'acetaminofen': 'N02',
  'acetaminofen **': 'N02',
  'acetaminofen dc equivalenteacetaminofen': 'N02',
  'acetaminofen granulado dc': 'N02',
  'acetaminofen granulos dc equivalentes acetaminofen': 'N02',
  'acetaminofen polvo': 'S01',
  'acetazolamida': 'S01',
  'acetil cisteina': 'R05',
  'acetilcisteina': 'R05',
  'acetonido triamcinolona': 'R01',
  'aciclovir': 'J05',
  'aciclovir polvo': 'J05',
  'acido acetico': 'G01',
  'acido acetil salicilico': 'N02',
  'acido acetil salicilico*': 'B01',
  'acido acetilsalicilico': 'B01',
  'acido acetilsalicilico granulado ref equivalentea acido acetilsalicilico': 'B01',
  'acido alendronico': 'M05',
  'acido alfa lipoico': 'A16',
  'acido alginico': 'A02',
  'acido aminoacetico': 'B05',
  'acido ascorbico': 'A11',
  'acido ascorbico ascorbato equivalentes acido ascorbico': 'A11',
  'acido ascorbico ascorbato equivalentes vitamina c': 'A11',
  'acido ascorbico ascorbato mgequivalentes vitamina c': 'A11',
  'acido ascorbico composicion los microgranulos acido ascorbico azucar goma laca acido tartarico talco alcohol etilico': 'A11',
  'acido ascorbico compresion directa': 'A11',
  'acido ascorbico grado inyectable': 'A11',
  'acido ascorbico malla especial': 'A11',
  'acido ascorbico recubierto': 'A11',
  'acido aspartico': 'B05',
  'acido azelaico': 'D10',
  'acido benzoico': 'D02',
  'acido borico': 'S02',
  'acido carglumico': 'A16',
  'acido citrico': 'A02',
  'acido citrico polvo': 'A02',
  'acido clavulanico': 'J01',
  'acido clavulanico celulosa microcristalina': 'J01',
  'acido clavulonico': 'J01',
  'acido colico': 'A05',
  'acido decosa hexaenoico': 'A11',
  'acido decosahexaenoico al equivalentes dha': 'A11',
  'acido dietilen triamino pentaacetico': 'V09',
  'acido dietilentriaminopentaacetico': 'V09',
  'acido dimercaptosuccinico': 'V09',
  'acido estearico': 'C09',
  'acido fenofibrico': 'C10',
  'acido fenofibrico **': 'C10',
  'acido folico': 'B03',
  'acido folinico': 'V03',
  'acido fusidico': 'D06',
  'acido gadoterico': 'V08',
  'acido gadoterico correspondiente dota oxido gadolinio': 'V08',
  'acido gadoterico meglumina': 'V08',
  'acido gamma linoleico acido cis linoleico': 'A11',
  'acido glicolico': 'D11',
  'acido glutamico': 'B05',
  'acido hialuronico sal': 'M09',
  'acido ibandronico': 'M05',
  'acido ibandronico exceso': 'M05',
  'acido lactico': 'D01',
  'acido libre': 'J01',
  'acido malico': 'B05',
  'acido medronico': 'V09',
  'acido mefenamico': 'M01',
  'acido metilen difosfonico': 'V09',
  'acido micofenolico': 'L04',
  'acido n iminodiacetico': 'V09',
  'acido orotico': 'A05',
  'acido pentetico': 'V09',
  'acido pipemidico': 'J01',
  'acido pipemidico equivalentes mgde acido pipemidico': 'J01',
  'acido poliacrilico': 'S01',
  'acido retinoico': 'D11',
  'acido salicilico': 'D01',
  'acido tartarico libre': 'A06',
  'acido tioctico': 'A16',
  'acido tranexamico': 'B02',
  'acido undecilenico': 'D01',
  'acido ursodeoxicolico': 'A05',
  'acido ursodesoxicolico': 'A05',
  'acido valproico': 'N03',
  'acido zoledronico': 'M05',
  'acido zoledronicoanhidro': 'M05',
  'acido zolendronico': 'M05',
  'acidodocosahexaenoico al *****': 'A11',
  'acidofusidico': 'D06',
  'acidos grasos omega': 'B05',
  'acidos grasos polinsaturados omega': 'C10',
  'acidos omega al': 'C10',
  'acidos omega etil ester': 'C10',
  'acidosalicilico': 'D10',
  'acidosgrasos omega': 'B05',
  'acidozoledronico': 'M05',
  'acliclovir': 'J05',
  'acyclovir': 'J05',
  'adalapeno': 'D10',
  'adalimumab': 'L04',
  'adapalene': 'D10',
  'adapaleno': 'D10',
  'adenosina': 'C01',
  'adrenalina': 'C01',
  'aescina': 'C05',
  'afatinib': 'L01',
  'aflibercept': 'S01',
  'agalsidasa alfa': 'A16',
  'agalsidasa beta': 'A16',
  'agomelatina': 'N06',
  'agua esteril': 'V07',
  'agua esteril apirogena': 'V07',
  'agua esteril para inyeccion': 'V07',
  'agua esteril para lavar heridas irrigacion': 'V07',
  'agua grado inyectable s p c s p': 'V07',
  'agua para inyeccion': 'V09',
  'agua purificada': 'C09',
  'aire': 'V03',
  'alanina': 'B05',
  'alanina glutamina': 'B05',
  'alantoina': 'V08',
  'albendazol': 'P02',
  'albendazol polvo': 'P02',
  'albumina': 'B05',
  'albumina humana': 'B05',
  'albumina serica humana nanocoloide': 'V09',
  'albuminahumana': 'B05',
  'alcaftadina': 'S01',
  'alcanfor': 'C01',
  'alcanfor sintetico': 'D11',
  'alcohol antiseptico': 'D08',
  'alcohol bencilico': 'D04',
  'alcohol cetoestearilico': 'N01',
  'alcohol diclorobencilico': 'R02',
  'alcohol etilico': 'D08',
  'alcohol etilico al': 'D08',
  'alcohol etilico gl': 'D08',
  'alcohol etilico impotabilizado': 'D08',
  'alcohol etilico impotabilizado gl': 'D08',
  'alcohol isopropilico': 'D08',
  'alcohol isopropilico para una concentracion final v v': 'D08',
  'alcohol polivinilico': 'S01',
  'alectinib': 'L01',
  'alemtuzumab': 'L04',
  'alfa antitripsina': 'B02',
  'alfa cetoanalogo fenilalanina': 'B05',
  'alfa cetoanalogo isoleucina': 'B05',
  'alfa cetoanalogo leucina': 'B05',
  'alfa cetoanalogo valina': 'B05',
  'alfa hidroxianalogo metionina butirato': 'B05',
  'alfuzosina': 'G04',
  'alginato': 'A02',
  'alginato phu': 'A02',
  'alginato phu nf al': 'A02',
  'alglucosidasa alfa': 'A16',
  'alirocumab': 'C10',
  'alizaprida': 'A03',
  'alizaprida equivalentes alizaprida': 'A03',
  'almidon glicolato': 'C09',
  'almidon maiz': 'C09',
  'almidon pregelatinizado': 'R06',
  'alopurinol': 'M04',
  'alprazolam': 'N05',
  'alprostadil': 'C01',
  'alquitran hulla': 'D11',
  'alteplase': 'B01',
  'aluminio': 'D02',
  'aluminio basico': 'D02',
  'aluminio hidroxido magnesio carbonato gel coprecipitado': 'A02',
  'alverina': 'A03',
  'amantadina': 'N04',
  'ambrisentan': 'C02',
  'ambroxol': 'R05',
  'amikacina': 'J01',
  'amilmetacresol': 'R02',
  'aminofilina': 'R03',
  'amiodarona': 'C01',
  'amisulprida': 'N05',
  'amitriptilina': 'N06',
  'amitriptilinaclorhidrato': 'N06',
  'amlodipino': 'C08',
  'amlodipino besilatoequivaleaamlodipinobase': 'C08',
  'amlodipino corresponde amlodipino': 'C09',
  'amlodipino correspondiente amlodipino': 'C09',
  'amlodipino equivalentea amlodipino': 'C09',
  'amlodipino equivalentes amlodipino': 'C08',
  'amlodipino libre': 'C09',
  'amlodipino mgequivalentes amlodipino': 'C09',
  'amlodipinobesilatoequivalentea amlodipino': 'C08',
  'amlopino': 'C08',
  'amolodipino': 'C09',
  'amorolfina': 'D01',
  'amoxicilina': 'J01',
  'amoxicilina *': 'J01',
  'amoxicilina deshidratada': 'J01',
  'amoxicilina equivalentes amoxicilina': 'J01',
  'amoxicilina polvo expresada amoxicilina': 'J01',
  'amoxicilina polvocompactada grado': 'J01',
  'amoxicilina trihidratada': 'J01',
  'amoxicilinaanhidra': 'J01',
  'amoxicilinabase': 'J01',
  'ampicilina': 'J01',
  'ampicilina euivalente ampicilina': 'J01',
  'ampicilina sulbactam': 'J01',
  'ampicilina trihidratocompactada': 'J01',
  'ampicilinaanhidra': 'J01',
  'ampilicina': 'J01',
  'ampolleta contiene clindamicina clindamicina': 'J01',
  'anastrazol': 'L02',
  'anastrozol': 'L02',
  'anfotericina b': 'J02',
  'anfotericina b liposomal': 'J02',
  'anidulafungina': 'J02',
  'anifrolumab': 'L04',
  'anlodipino': 'C09',
  'antigeno hbsag purificado recombinante': 'J07',
  'antigeno prefusion f estabilizado virus respiratorio sincitial subgrupo': 'J07',
  'antigeno prefusion f estabilizado virus respiratorio sincitial subgrupo b': 'J07',
  'antigeno superficial purificado hepatitis b': 'J07',
  'antigeno superficial virus hepatitis b obtenido por tecnologia deladnr': 'J07',
  'antigeno superficie virus hepatitis b': 'J07',
  'antigeno superficie virus hepatitis b hbsag purificado': 'J07',
  'antigeno superficie virus hepatitis b recombinante': 'J07',
  'antigeno virus hepatitis': 'J07',
  'antigenos bordetella pertusis hemaglutinina filamentosa': 'J07',
  'antigenos bordetella pertusis toxoide pertusico': 'J07',
  'antigenos bordetella pertussis toxoide pertusico': 'J07',
  'antipirina': 'N01',
  'apalutamida': 'L02',
  'apalutamida equivalentes apalutamida': 'L02',
  'apixaban': 'B01',
  'apomorfina': 'N04',
  'aprepitant': 'A04',
  'aprotinina pulmon bovino': 'B02',
  'arginina': 'B05',
  'arginina perindopril': 'C09',
  'aripiprazol': 'N05',
  'aripiprazolmicronizado': 'N05',
  'artemetero': 'P01',
  'articaina': 'A01',
  'asciminib': 'L01',
  'ascorbato': 'A11',
  'ascorbato equivalentes acido ascorbico': 'A11',
  'asfotasa alfa': 'A16',
  'aspirina': 'B01',
  'atazanavir': 'J05',
  'atazanavir equivalentes atazanavir': 'J05',
  'atezolizumab': 'L01',
  'atogepant': 'N02',
  'atorvas tatina': 'C10',
  'atorvastatina': 'C10',
  'atorvastatina calcio': 'C10',
  'atorvastatina equivalentea atorvastatina': 'C10',
  'atorvastatina hidrato': 'C10',
  'atorvastatina mgequiv atorvastatina': 'C10',
  'atorvastatinacomo atorvastatinacalcica': 'C10',
  'atosiban': 'G02',
  'atropina': 'A03',
  'atropinasulfato': 'A03',
  'avalglucosidasa alfa': 'A16',
  'avanafil': 'G04',
  'avelumab': 'L01',
  'avibactam': 'J01',
  'axetilo cefuroxima': 'J01',
  'axitinib': 'L01',
  'azacitidina': 'L01',
  'azatioprina': 'L04',
  'azelastina': 'R01',
  'azelastina hcl': 'R01',
  'aziromicina': 'J01',
  'azitromicina': 'J01',
  'azitromicina azitromicina': 'J01',
  'azitromicina dihidratada equivalentes azitromicina': 'J01',
  'azitromicina equivalentes azitromicina': 'J01',
  'azitromicina*': 'J01',
  'aztreonam': 'J01',
  'azufre': 'D10',
  'azufre precipitado': 'D02',
  'azul metileno': 'V03',
  'b austria cepa analoga': 'J07',
  'b phuket cepa analoga': 'J07',
  'bacavir': 'J05',
  'bacillus clausii': 'A07',
  'bacilluscalmetteguerin': 'L03',
  'bacitracina zinc': 'S01',
  'baclofen': 'M03',
  'baclofeno': 'M03',
  'baricitinib': 'L04',
  'bario': 'V08',
  'basiliximab': 'L04',
  'beclametasona': 'A07',
  'beclometasona': 'R03',
  'belatacept': 'L04',
  'belimumab': 'L04',
  'bencetonio cloruro': 'D08',
  'bencidamina': 'A01',
  'bencidamina hcl': 'A01',
  'bencilpenicilina benzatinica': 'J01',
  'bendamustina': 'L01',
  'benfotiamina': 'A11',
  'benoxinato': 'S01',
  'benoxinato hcl': 'R02',
  'benralizumab': 'R03',
  'benzidamina': 'A01',
  'benzilpenicilina benzatinica': 'J01',
  'benznidazol': 'P01',
  'benzoato bencilo': 'P03',
  'benzocaina': 'R02',
  'benzoil metronidazol': 'P01',
  'benzoilmetronidazol equivalenteametronidazol': 'P01',
  'benzoilo peroxido': 'D10',
  'bepotastina': 'S01',
  'berotralstat': 'B06',
  'beta metil digoxina': 'C01',
  'betacaroteno': 'A11',
  'betacaroteno al': 'A11',
  'betahistina': 'N07',
  'betahistinaclorhidrato': 'N07',
  'betahistinadicloruro': 'N07',
  'betahstina': 'N07',
  'betaina depolvo': 'A16',
  'betametasona': 'H02',
  'betametasona * *': 'D07',
  'betametasona disodico': 'H02',
  'betametasona disodio': 'S01',
  'betametasona eq betametasona': 'D07',
  'betametasona equivalante betametasona': 'D07',
  'betametasona equivalentes betametasona': 'D07',
  'betametasona equivelente betametasona': 'D07',
  'betametasona euivalente betametasona': 'D07',
  'betametasona valeratocomo betametasonabase': 'D07',
  'betametasonabase': 'D05',
  'betametasonavalerato': 'D07',
  'betametildigoxina': 'C01',
  'betametsa bas': 'D07',
  'betiatida': 'V09',
  'bevacizumab': 'L01',
  'bevacizumab solucion concentrada para infusion': 'L01',
  'bicalutamida': 'L02',
  'bicarbonato': 'A02',
  'bicarbonato esteril': 'J01',
  'bicarbonatodesodio': 'A02',
  'bictegravir bictegravir': 'J05',
  'bifidobacteria minimo': 'G01',
  'bifonazol': 'D01',
  'bilastina': 'R06',
  'bimatoprost': 'S01',
  'bimonidrina': 'S01',
  'binimetinib': 'L01',
  'biotina': 'A11',
  'biperideno': 'N04',
  'bisacodilo': 'A06',
  'bisoprolol': 'C07',
  'bisopropol': 'C07',
  'blanda contiene acido fenofibrico': 'C10',
  'blanda contiene rosuvastatina': 'C10',
  'bleomicina': 'L01',
  'blinatumomab': 'L01',
  'bornanona': 'D11',
  'bortezomib': 'L01',
  'bosentan': 'C02',
  'bosutinib': 'L01',
  'bosutinib equivalentebosutinib': 'L01',
  'brentuximab vedotin': 'L01',
  'brigatinib': 'L01',
  'brimonidina': 'S01',
  'brinzolamida': 'S01',
  'brivaracetam': 'N03',
  'bromazepam': 'N05',
  'bromexina': 'R05',
  'bromfenaco': 'S01',
  'bromfenaco acido': 'S01',
  'bromhexina': 'R05',
  'bromhexina clorhiddrato': 'R05',
  'bromhexina hcl': 'R05',
  'buclizina': 'R06',
  'buclizinaclorhidrato': 'R06',
  'budesonida': 'R03',
  'bupicaina': 'N01',
  'bupivacaina': 'N01',
  'bupivacaina bupivacaina': 'N01',
  'buprenorfina': 'N02',
  'bupropion': 'N07',
  'burosumab': 'M05',
  'busulfan': 'L01',
  'butenafina': 'D01',
  'butil hioscina': 'A03',
  'butilbromuro hioscina': 'A03',
  'c urea': 'V04',
  'cabazitaxel': 'L01',
  'cabazitaxel solvato acetonico': 'L01',
  'cabergolina': 'G02',
  'cabozantinib': 'L01',
  'cafeina': 'M01',
  'cafeina annhidra': 'N02',
  'cafeina polvo': 'A02',
  'cafeinaanhidra': 'N02',
  'calamina': 'C05',
  'calcio': 'A11',
  'calcio aluminio equivalentes aluminio': 'D02',
  'calcio carbonato': 'A02',
  'calcio cloruro dihidratado': 'B05',
  'calcio equivalentes calcio': 'A12',
  'calcio granulado': 'A11',
  'calcio granulado calcio': 'A11',
  'calcio mgcomo calcio citratotetrahidratado': 'A12',
  'calciox h': 'A12',
  'calcipotriol': 'D05',
  'calcitriol': 'A11',
  'camara aceite soya refinado': 'B05',
  'camara alanina': 'B05',
  'camara emulsion lipidica aceite soya refinado': 'B05',
  'camara glucosa': 'B05',
  'camara glucosa glucosamonohidrato': 'B05',
  'camara solucion aminoacidos alanina': 'B05',
  'camsilato amlodipino equivalentes amlodipino': 'C09',
  'canakinumab': 'L04',
  'candesartan cilexetil': 'C09',
  'candesartan cilexetilo': 'C09',
  'cannabidiol': 'N03',
  'cannabidiol cbd cristales': 'N03',
  'cannabidiol equivante cbd': 'N02',
  'caolin': 'A07',
  'cap acido eicosapentaenoico capde acido docosahexaenoico': 'A11',
  'cap calcio': 'A11',
  'cap hierro': 'A11',
  'cap molibdeno': 'A11',
  'cap zinc': 'A11',
  'capa medicamento metilfenidato': 'N06',
  'capecitabina': 'L01',
  'caplacizumab': 'B01',
  'capsaicina': 'N01',
  'capsulablandacontiene naproxeno': 'N02',
  'captopril': 'C09',
  'carbacol': 'S01',
  'carbamazepina': 'N03',
  'carbetocina': 'H01',
  'carbidopa': 'N04',
  'carbidopa monohidratada granulos': 'N04',
  'carbocisteina': 'R05',
  'carbodopa': 'N04',
  'carbon activado': 'A07',
  'carbonato': 'S02',
  'carbonato calcio': 'A02',
  'carbonato calcio equivalenteacalcio': 'A12',
  'carbonato calcio equivalentes calcio': 'A02',
  'carbonato calcio pesado ca': 'A11',
  'carbonato calcio pesado equivalentes calcio': 'A11',
  'carbonato calcio precipitado': 'A02',
  'carbonato hidrogeno': 'A02',
  'carbonato litio': 'N05',
  'carbonato magnesio liviano': 'A12',
  'carboplatino': 'L01',
  'carboximetil celulosa': 'S01',
  'carboximetilcelulosa': 'S01',
  'carboximetilcelulosa sodicac equvalentes carboximetil celulosa total': 'S01',
  'carboximetilcisteina': 'R05',
  'carfilzomib': 'L01',
  'carmustina': 'L01',
  'carvedilol': 'C07',
  'caspofungina': 'J02',
  'caspofungina equivalentes caspofungina': 'J02',
  'caspofungina libre': 'J02',
  'caspofunginabaseanhidra': 'J02',
  'casponfungina': 'J02',
  'cefadroxilo': 'J01',
  'cefalexina': 'J01',
  'cefalexinabase': 'J01',
  'cefalotina': 'J01',
  'cefalotina esteril': 'J01',
  'cefalozina': 'J01',
  'cefazolina': 'J01',
  'cefazolina basica': 'J01',
  'cefditoren': 'J01',
  'cefdroxilo': 'J01',
  'cefepima': 'J01',
  'cefepime': 'J01',
  'cefepime para inyeccion': 'J01',
  'cefotaxima': 'J01',
  'cefpodoxime': 'J01',
  'cefpodoxime proxetil eq to cefpodoxime': 'J01',
  'cefpodoxime proxetil eq tocefpodoxime': 'J01',
  'cefradilo equivalentes cefradilo': 'J01',
  'cefradina': 'J01',
  'cefradina compactada': 'J01',
  'cefradinayl arginina equivalentes cefradina baseesteril': 'J01',
  'ceftarolina fosamilo': 'J01',
  'ceftazidima esteril': 'J01',
  'ceftazidime': 'J01',
  'ceftibuteno por depolvo': 'J01',
  'ceftolozano': 'J01',
  'ceftriaxona': 'J01',
  'ceftriaxona disodica hemiheptahidratada ceftriaxona': 'J01',
  'ceftriaxona hemitrihidratada hemiheptahidratada disodica ceftriaxona': 'J01',
  'cefuroxima': 'J01',
  'celecoxib': 'M01',
  'celulosa microcristalina': 'N06',
  'celulosa microcristalina ph': 'C02',
  'cerliponasaalfa': 'A16',
  'certolizumabpegol': 'L04',
  'cetaminofen': 'N02',
  'ceterizina': 'N02',
  'cetil trimetilamonio': 'D08',
  'cetilpiridinio': 'R02',
  'cetilpiridinio cloruro': 'R02',
  'cetirizina': 'R06',
  'cetirizina di': 'N02',
  'cetirizina diclorhidrado': 'R06',
  'cetirizina hcl': 'M01',
  'cetirizina microgranulos al liberacion inmediata equivalentes cetirizina': 'R01',
  'cetrimida': 'D08',
  'cetrorelix': 'H01',
  'cetuximab': 'L01',
  'champiojo cipermetrina': 'P03',
  'cianocobalamina': 'B03',
  'ciclesonida': 'R03',
  'ciclobenzaprina': 'M03',
  'ciclofosfamida': 'L01',
  'ciclonamina': 'B02',
  'ciclopentolato': 'S01',
  'ciclopirox': 'D01',
  'ciclopirox olamina': 'D01',
  'ciclosilicato zirconio': 'V03',
  'ciclosporina': 'L04',
  'cido fusidico': 'D06',
  'cilastatina': 'J01',
  'cilostazol': 'B01',
  'cinacalcet': 'H05',
  'cinacalcet clorhidratoequivalente cinacalcet': 'H05',
  'cinarizina': 'N07',
  'cinitaprida': 'A03',
  'cipermetrina': 'P03',
  'cipionato estradiol': 'G03',
  'ciprofibrato': 'C10',
  'ciprofloxacina': 'J01',
  'ciprofloxacina ciprofloxacina': 'J01',
  'ciprofloxacino': 'J01',
  'ciprofloxacino equivalentea ciprofloxacino': 'J01',
  'ciprofloxacino granulado c d equivalentes ciprofloxacino': 'J01',
  'ciproheptadina': 'R06',
  'ciproterona': 'G03',
  'cisatracurio': 'M03',
  'cisplatino': 'L01',
  'cisteamina': 'A16',
  'cisteina': 'B05',
  'citarabina': 'L01',
  'citicolina': 'N06',
  'citicolina equivalenteciticolina': 'N06',
  'citicolina sal sodicaquivalente citicolina': 'N06',
  'cladribina': 'L01',
  'claritromicina': 'J01',
  'claritromicina microencapsulada': 'J01',
  'claritromicina microencapsulada equivalentes claritromicina': 'J01',
  'claritromicina polvo': 'J01',
  'claritromicinamicropellets al equivalentes claritromicina': 'J01',
  'clavulanato': 'J01',
  'clavulanato dioxido silicio equvalente acido clavulanico': 'J01',
  'clavulanato syloid expresado acido clavulanico': 'J01',
  'clavulonato diluido con dioxido silicio equivalante acido clavulanico': 'J01',
  'clavulonato potasioequivalenteaacido clavulanico': 'J01',
  'clemastina': 'R06',
  'clembuterol': 'R05',
  'clenbuterol': 'R03',
  'clindamicina': 'J01',
  'clindamicina equivalentes clindamicina': 'J01',
  'clindamicinabase': 'G01',
  'clindamicinafosfato': 'G01',
  'clioquinol': 'D07',
  'clobazam': 'N05',
  'clobetasol': 'D07',
  'clobetasol propionatoequivalenteaclobetasolpropionatoanhidro': 'D07',
  'clobetasolpropionato': 'D07',
  'clobetazol': 'D07',
  'clofarabina': 'L01',
  'clofazimina': 'J04',
  'clonazepam': 'N03',
  'clonidina': 'C02',
  'clonixinato lisina': 'A03',
  'clonxinato lisina pargeverina': 'A03',
  'cloperastina hcl': 'R05',
  'cloperastinaclorhidrato': 'R05',
  'clopidogrel': 'B01',
  'clopidrogel': 'B01',
  'clorambucilo': 'L01',
  'cloranfenicol': 'J01',
  'clorefeniramina': 'R06',
  'clorfenamina': 'N02',
  'clorfenilamina': 'N02',
  'clorfeniramina': 'R06',
  'clorfeniraminamaleato': 'R06',
  'clorhexidina': 'D08',
  'clorhexidina al': 'D08',
  'clorhexidina digluconato': 'D08',
  'clorhexidina equivalentes clorhexidina': 'D08',
  'clorhexidina solucional equivalentea clorhexidina': 'D08',
  'clorhexidinadigluconato equivalentea clohexidinadigluconato': 'D08',
  'clorhidratodetramadol': 'N02',
  'clorimazol': 'G01',
  'clormadinona': 'G03',
  'clormetina': 'L01',
  'clorocresol': 'D08',
  'cloroquina': 'P01',
  'clortalidona': 'C03',
  'cloruro': 'B05',
  'cloruro *': 'A07',
  'cloruro acetil colina': 'S01',
  'cloruro amonio': 'R03',
  'cloruro benzalconio': 'D08',
  'cloruro calcio': 'B05',
  'cloruro calcio dihidratado': 'B05',
  'cloruro calcio h': 'B05',
  'cloruro cetil piridinio': 'R02',
  'cloruro cetilpiridinio': 'R02',
  'cloruro cetilpiridino': 'R02',
  'cloruro citilpiridinio': 'R02',
  'cloruro cobre * h': 'B05',
  'cloruro cobre dihidratado': 'B05',
  'cloruro cromico hexahidratado': 'B05',
  'cloruro cromo': 'A11',
  'cloruro cromo hexahidratado': 'B05',
  'cloruro decalciodihidrato': 'B05',
  'cloruro decualinio': 'R02',
  'cloruro demagnesio hexahidrato': 'B05',
  'cloruro depotasio': 'A07',
  'cloruro ferrico hexahidrato': 'B05',
  'cloruro hierro': 'B05',
  'cloruro magnesio': 'B05',
  'cloruro magnesio h': 'B05',
  'cloruro magnesio haxahidratado': 'B05',
  'cloruro magnesio hexahidratado': 'B05',
  'cloruro magnesio hexahidrato': 'B05',
  'cloruro magnsio h': 'V07',
  'cloruro manganeso': 'B05',
  'cloruro manganeso * h': 'B05',
  'cloruro manganesotetrahidratado': 'B05',
  'cloruro margnesico hexahidrato': 'B05',
  'cloruro mivacurio': 'M03',
  'cloruro pulverizado': 'B05',
  'cloruro trospio': 'G04',
  'cloruro zinc': 'B05',
  'clorurode': 'B05',
  'clorurode calcio': 'B05',
  'clorurode magnesio hexahidratado': 'B05',
  'clorurodesodio': 'B05',
  'clostridium botulinum toxina tipo unidades': 'M03',
  'clotrimazol': 'G01',
  'clotrimazol *': 'D07',
  'clozapina': 'N05',
  'clrofeniramina': 'R05',
  'cobalto': 'A11',
  'cobicistat': 'J05',
  'cobicistat dioxido silicio equivalentes cobicistat': 'J05',
  'cobimetinib equivalentes cobimetinib': 'L01',
  'cobre': 'A11',
  'cocarboxilasa tetrahidratada': 'A11',
  'codeina': 'N02',
  'codeina codeina': 'N02',
  'codeina hemidrato': 'N02',
  'codeina hemidrato codeina': 'N02',
  'codeina hemihidratado': 'R05',
  'codeinafosfato': 'N02',
  'colageno hidrolizado': 'M01',
  'colchicina': 'M04',
  'colecalciferol': 'A11',
  'colecalciferol equivalentes': 'A11',
  'colecalciferol vit d': 'A11',
  'colestiramina resina': 'C10',
  'colistimetato': 'A07',
  'colistina': 'J01',
  'color amarillo # d&c': 'N02',
  'color azl no': 'B05',
  'compartimiemto i somatropina *': 'H01',
  'compartimiento aminoacidos': 'B05',
  'compartimiento aminoacidos con electrolitos alanina': 'B05',
  'compartimiento emulsion lipidica': 'B05',
  'compartimiento lipidos aceite soja refinado aceite oliva refinado': 'B05',
  'compartimiento solucion glucosa': 'B05',
  'complejo hemaglutinina toxina tipo clostridium botulinum': 'M03',
  'complejo toxina tipo clostridium botulinum': 'M03',
  'componente aprotinina': 'B02',
  'componente cloruro calcio': 'B02',
  'componente fibrinogeno humano': 'B02',
  'componente trombina humana': 'B02',
  'composicion microgranulos lansoprazol': 'A02',
  'comprimidos con activo *drospirenona': 'G03',
  'concentrado enzimas proteoliticas enriquecidas bromelaina': 'D03',
  'condroitin': 'M01',
  'condroitina': 'M01',
  'contenido calcifediol': 'A11',
  'contiene acetaminofen': 'N02',
  'contiene carvedilol': 'C07',
  'contiene liofilizado estandardizado correspondientes lisados bacterianos liofilizados pneumoniae klebsiella pneumoniae ssp pneumoniae ssp ozaenae staphylococcus aureus streptococcuspyogenes sanguinis moraxella catarrhalis': 'R07',
  'contiene lutecio cloruro lutecio con una actividad que oscila entre gbq lo que se corresponde con microgramos lutecio fecha hora calibracion volumen oscila entre': 'V10',
  'contiene mil millones celulas muertas lactobacillus fermentum lactobacillus delbrueckii medio cultivo fermentado neutralizado equivalentes': 'A07',
  'contiene pinaverio': 'A03',
  'contiene sal mebrofenina': 'V09',
  'contiene tetrakis tetrafluoroborato para ser marcado con radioisotopo mtc': 'V09',
  'coriogonadotropinaalfa': 'G03',
  'crizotinib': 'L01',
  'crm': 'J07',
  'cromo amino acido quelato': 'A11',
  'cromoglicato': 'S01',
  'croscarmelosa': 'C02',
  'croscermelosa': 'L04',
  'crotamiton': 'P03',
  'cubierta agua purificada': 'N02',
  'cubierta gelatina': 'N02',
  'cubierta solucion sorbitol sorbitan': 'N02',
  'cuprico': 'A12',
  'd biotina': 'A11',
  'd exametazima': 'V09',
  'd glucosamina': 'M01',
  'd pantenol': 'A11',
  'dabigatran etexilato': 'B01',
  'dabigatran etexilato dabigatran etexilato': 'B01',
  'dabrafenib libre': 'L01',
  'dacarbazina': 'L01',
  'dactinomicina': 'L01',
  'dalteparina': 'B01',
  'dalteparinasodica': 'B01',
  'danazol': 'G03',
  'dapagliflozina': 'A10',
  'dapagliflozina propanodiol': 'A10',
  'dapaglifozina': 'A10',
  'dapoxetina': 'G04',
  'dapsona': 'J04',
  'daptomicina': 'J01',
  'daratumumab': 'L01',
  'darbepoetina alfa': 'B03',
  'darifenacina': 'G04',
  'darolutamida': 'L02',
  'darunavir': 'J05',
  'darunavir *': 'J05',
  'darunavir etanolato': 'J05',
  'darunavir etanolato equivalentes darunavir': 'J05',
  'dasatinib': 'L01',
  'dasatinib anhidrido': 'L01',
  'daunorubicina': 'L01',
  'deamoxicilinabase': 'J01',
  'decanoato nandrolona': 'A14',
  'decitabina': 'L01',
  'dedexametasona': 'S03',
  'deetilefrina': 'C01',
  'deferasirox': 'V03',
  'deferiprona': 'V03',
  'deflazacort': 'H02',
  'deflazacortmicronizado': 'H02',
  'defluorometalona': 'S01',
  'degarelix': 'L02',
  'deion zinc': 'A12',
  'delafloxacino': 'J01',
  'delta tetrahidrocannabinol equivante thc': 'N02',
  'demedroxiprogesterona': 'G03',
  'denosumab': 'M05',
  'depolvo para suspension oralcontine rifaximina': 'A07',
  'depotasio': 'A07',
  'desasonida': 'D07',
  'desflurano': 'N01',
  'desflurano v v liquido para vapor': 'N01',
  'desilimarina calculadocomo silibina': 'A05',
  'deslansoprazol': 'A02',
  'desloradina': 'N02',
  'desloratadina': 'R06',
  'desloratadina microgranulos*': 'R01',
  'desmopresina': 'H01',
  'desodio': 'B05',
  'desogestrel': 'G03',
  'desonida': 'D07',
  'desultamicilina': 'J01',
  'desvenlafaxina': 'N06',
  'desvenlafaxina exceso': 'N06',
  'determinadas mediante tiempo tromboplastina parcial activada': 'C05',
  'detizanidina': 'M03',
  'deucravacitinib': 'L04',
  'dex': 'D07',
  'dexametasiona': 'S01',
  'dexametasona': 'H02',
  'dexametasona eq dexametasona': 'D07',
  'dexametasona equiv dexametasona': 'H02',
  'dexametasona equivalentes dexametasona': 'H02',
  'dexametasona esteril': 'S01',
  'dexametasona expresado dexametasona': 'D07',
  'dexametasonaacetato': 'D07',
  'dexametasonabase': 'D07',
  'dexametasonafosfato': 'H02',
  'dexametasonasodio': 'S01',
  'dexametasonasodio equiv dexametasona': 'H02',
  'dexclorfeniramina': 'N02',
  'dexibuprofeno': 'M01',
  'dexketoprofeno': 'M01',
  'dexketoprofeno trometamol': 'M01',
  'dexketroprofeno': 'M01',
  'dexlansoprazol': 'A02',
  'dexlansoprazolanhidro': 'A02',
  'dexlanzoprazol': 'A02',
  'dexmedetomidina': 'N05',
  'dexmedetomidina equivalentes dexmedetomidina': 'N05',
  'dexpantenol': 'A11',
  'dexrazoxane': 'V03',
  'dextran': 'S01',
  'dextrometorfano': 'R05',
  'dextrometorfano bromhidra to': 'R05',
  'dextrometorfano bromohidrato': 'R05',
  'dextrometorfano hidrobromuro': 'R01',
  'dextrometorfanobromhidrato': 'R05',
  'dextrosa': 'B05',
  'dextrosa al': 'C01',
  'dextrosa equivalentes dextrosa': 'B05',
  'dextrosa glucosaanhidra': 'N01',
  'dextrosa grado parenteral': 'N01',
  'dextrosa hidratada': 'B05',
  'dextrosaanhidra': 'B05',
  'diacereina': 'M01',
  'diatrizoato': 'V08',
  'diazepam': 'N05',
  'diazoxido': 'V03',
  'dibasico': 'H02',
  'dibasico calcio': 'A11',
  'diclofenac': 'R05',
  'diclofenaco': 'M01',
  'diclofenaco dietilamino diclofenaco': 'M02',
  'diclofenaco dietilamonio': 'M01',
  'diclofenacodietilamino': 'M01',
  'diclofenacosodico': 'M01',
  'dicloxacilina': 'J01',
  'dicloxacilinabase': 'J01',
  'didrogesterona': 'G03',
  'dienogest': 'G03',
  'difenhidramina': 'R06',
  'difenhidramina hcl': 'R06',
  'difenhidraminaclorhidrato': 'R06',
  'difenoxilato': 'A07',
  'diflucortolona m': 'D07',
  'difluprednato': 'D07',
  'digluconato clorhexidina para una concentracion final digluconato clorhexidina': 'D08',
  'dihidratado': 'B05',
  'dihidrocloruro pramipexol': 'N04',
  'dihidrocodeina': 'N02',
  'dihidrocodeina bitartato': 'N02',
  'dihidrogeno dihidratado': 'B05',
  'diltiazem': 'C08',
  'dimenhidrinato': 'R06',
  'dimetico': 'A03',
  'dimeticona': 'A03',
  'dimeticona al': 'A02',
  'dimetil': 'N07',
  'dimetilfumarato': 'L04',
  'dimetilpolisiloxano': 'A03',
  'dimetilpolisoxano': 'A09',
  'dinitrato isosorbida': 'C01',
  'dinitrato isosorbide': 'C01',
  'dinoprostona': 'G02',
  'diosmectita': 'A07',
  'diosmina': 'C05',
  'diosmina flavonoides expresado hesperidina': 'C05',
  'diosmina flavonoides expresados hesperidina': 'C05',
  'diosmina purificada': 'C05',
  'dioxido carbono medicinal': 'V03',
  'dioxido carbono no menos': 'V03',
  'dioxido siliicio coloidal': 'L04',
  'dioxido titanio': 'N06',
  'dipiridamol': 'B01',
  'dipirona': 'N02',
  'dipirona ep': 'N02',
  'dipirona magnesica': 'N02',
  'disodico dodecahidrato': 'B05',
  'disoproxilo tenofovir': 'J05',
  'divalproato': 'N03',
  'divalproato equivalenteaacidovalproico': 'N03',
  'dl alfa tocoferil': 'A11',
  'dl alfa tocoferil equivalentes vitamina': 'A11',
  'dl alfa tocoferol': 'A11',
  'dl alfatocoferil': 'A11',
  'dl alfatocoferil vit sintetica': 'A11',
  'dl alfatocoferil vitamina sintetica': 'A11',
  'dl alfatocoferol': 'A11',
  'dobesilato monohidratado': 'C05',
  'dobutamina': 'C01',
  'dobutamina equivalentes dobutamina': 'C01',
  'docetaxel': 'L01',
  'docusato': 'A06',
  'dolutegravir': 'J05',
  'domperidona': 'A03',
  'domperodina': 'A03',
  'donepecilo': 'N06',
  'donepezil': 'N06',
  'dopamina': 'C01',
  'doravirina': 'J05',
  'doripenem': 'J01',
  'dornasa desoxirribonucleasa i humana recombinante': 'R05',
  'dorzalamina': 'S01',
  'dorzolamida': 'S01',
  'dorzolamina': 'S01',
  'dos tabletas con ezetimiba una': 'C10',
  'dostarlimab': 'L01',
  'doxasozina': 'C02',
  'doxazosina': 'C02',
  'doxepina': 'N06',
  'doxiciclina': 'J01',
  'doxiciclina equivalentea doxiciclina': 'J01',
  'doxiciclinabase': 'J01',
  'doxiclina': 'J01',
  'doxilamina': 'N02',
  'doxofilina': 'R03',
  'doxorrubicina': 'L01',
  'doxorubicina': 'L01',
  'doxorubicina liposomal pegilada': 'L01',
  'doxorubicinaclorhidrato': 'L01',
  'dronabinol': 'A04',
  'dronedarona': 'C01',
  'drospirenona': 'G03',
  'drospirenona micro': 'G03',
  'droxidopa': 'C01',
  'dulaglutida': 'A10',
  'duloxetina': 'N06',
  'duloxetina duloxetina': 'N06',
  'duloxetina equivalete duloxetina': 'N06',
  'duloxetina granulos con recubrimiento enterico': 'N06',
  'dupilumab': 'D11',
  'durvalumab': 'L01',
  'dutasterida': 'G04',
  'dutasteride': 'G04',
  'dxtrosa': 'A07',
  'eculizumab': 'L04',
  'edetato calcio': 'V03',
  'efavirenz': 'J05',
  'eletriptan': 'N02',
  'eliglustat': 'A16',
  'elosulfasa alfa': 'A16',
  'eltrombopag': 'B02',
  'eltrombopag olamina eltrombopag acido libre eltrombopag': 'B02',
  'eltrombopag olaminaequivalentea eltrombopag acidolibre eltrombopag': 'B02',
  'elvitegravir': 'J05',
  'emicizumab': 'B02',
  'empagliflozina': 'A10',
  'emtricitabina': 'J05',
  'emtricitabine': 'J05',
  'emulsion lipidica aceite soya refinada trigliceridos cadena media aceite oliva refinado aceite pescado rico acidos omega': 'B05',
  'enalapril': 'C09',
  'enalaprilmaleato': 'C09',
  'enantato noretisterona': 'G03',
  'enantato testosterona': 'G03',
  'enantatodenoretisterona': 'G03',
  'encorafenib': 'L01',
  'enfortumab vedotina': 'L01',
  'enoxaparina': 'B01',
  'enoxaparinasodica': 'B01',
  'enoxoparina': 'B01',
  'entacapona': 'N04',
  'entacapone': 'N04',
  'entecavir': 'J05',
  'entecavir equivalentes entecavir': 'J05',
  'enterococcus faecium minimo': 'G01',
  'entrectinib': 'L01',
  'enzalutamida': 'L02',
  'epa dha disueltos gelatina blanda': 'C10',
  'epinastina': 'S01',
  'epinefrina': 'C01',
  'epirubicina': 'L01',
  'eplerenona': 'C03',
  'epoprostenol': 'B01',
  'ergotamina': 'N02',
  'eribulina': 'L01',
  'eritromicina': 'J01',
  'eritropoyetina alfa humana recombinante': 'B03',
  'eritropoyetina humana recombinante': 'B03',
  'eritropoyetina humana recombinante tipo alfa': 'B03',
  'eritropoyetina recombinante humana': 'B03',
  'eritropoyetina recombinante humana tipo beta': 'B03',
  'eritropoyetina rh humana recombinante': 'B03',
  'erlotinib': 'L01',
  'ertapenem': 'J01',
  'escitalopram': 'N06',
  'escitalopram oxalato equivalenteaescitalopram': 'N06',
  'escitalopram oxalato equivalentes escitalopram': 'N06',
  'escitalopram oxalato equivaletente escitalopram': 'N06',
  'esencia trementina': 'R01',
  'esomeprazol': 'A02',
  'esomeprazol equivalentes esomeprazol': 'A02',
  'esomeprazol magnesio pellets equivalentea esomeprazol': 'A02',
  'esomeprazol microgranulos* equivalentes esomeprazol': 'A02',
  'esomeprazol pellets al equivalentes esomeprazol': 'A02',
  'esomeprazol trihidratado equivalentea esomeprazol': 'A02',
  'espiramicina': 'J01',
  'espirinolactona': 'C03',
  'espironolactona': 'C03',
  'espironolactona micronizadausp': 'C03',
  'esporas bacillus clausii millones': 'A07',
  'esporas bacillus clausii resistente poli antibioticos': 'A07',
  'esteres etilicos los acidos grasos yodados no yodados aceite adormidera equivalentes yodo': 'V08',
  'estetrol': 'G03',
  'estiripentol': 'N03',
  'estradiol': 'G03',
  'estradiol dienogest': 'G03',
  'estradiolvalerato': 'G03',
  'estriol': 'G03',
  'estrogenos conjugados': 'G03',
  'eszopiclona': 'N05',
  'eszoplicona': 'N05',
  'etambutol': 'J04',
  'etamsilato': 'B02',
  'etanercept': 'L04',
  'etilefrina': 'C01',
  'etinil estradiol': 'G03',
  'etinilestradiol': 'G03',
  'etinilestradiol micro': 'G03',
  'etofenamato': 'M02',
  'etomidato': 'N01',
  'etonogestrel': 'G03',
  'etoposido': 'L01',
  'etoricoxib': 'M01',
  'etravirina': 'J05',
  'everolimus': 'L01',
  'everolimus bht': 'L04',
  'evogliptina': 'A10',
  'evolocumab': 'C10',
  'exametazima': 'V09',
  'exceso': 'M01',
  'exemestano': 'L02',
  'extracto bilis buey': 'A09',
  'extracto capsico capsicum frutescens': 'M02',
  'extracto flores arnica montana': 'M02',
  'extracto fluido ruibarbo': 'D01',
  'extracto ginseng al': 'A11',
  'extracto seco matricaria chamomilla': 'S01',
  'extractos alergenicos polimerizados acaros': 'V01',
  'ezatimiba': 'C10',
  'ezatimibe': 'C10',
  'ezetimiba': 'C10',
  'ezetimiba contiene tabletas una por': 'C10',
  'ezetimibe': 'C10',
  'factor antihemofilico humano': 'B02',
  'factor antihemofilico pegilado': 'B02',
  'factor coagulacion humano viii': 'B02',
  'factor coagulacion xiii': 'B02',
  'factor crecimiento epidermico humano recombinante fce hr': 'D03',
  'factor humano von willebrand': 'B02',
  'factor ii': 'B02',
  'factor ii coagulacion entre': 'B02',
  'factor ix': 'B02',
  'factor ix coagulacion': 'B02',
  'factor ix coagulacion plasma humano': 'B02',
  'factor ix coagulacion recombinante': 'B02',
  'factor ix coagulacion recombinante obtenido celulas cho': 'B02',
  'factor ix coagulacion recombinante rfix': 'B02',
  'factor ix coagulacion rfix': 'B02',
  'factor ix humano': 'B02',
  'factor vii': 'B02',
  'factor vii coagulacion entre': 'B02',
  'factor viia recombinante coagulacion eptacog alfa activado': 'B02',
  'factor viii': 'B02',
  'factor viii antihemofilico': 'B02',
  'factor viii antihemofilico pegilado': 'B02',
  'factor viii coagulacion humana': 'B02',
  'factor viii coagulacion humano': 'B02',
  'factor viii coagulacion humano recombinante simoctocog alfa': 'B02',
  'factor viii coagulacion humano recombinante turoctocog alfa': 'B02',
  'factor viii coagulacion humano valor nominal': 'B02',
  'factor viii coagulacion recombinante cadena unica': 'B02',
  'factor viii coagulacion recombinante octocog alfa': 'B02',
  'factor viii humano coagulacion turoctocog alfa': 'B02',
  'factor viii humano coagulacion turoctocog alfa recombinante': 'B02',
  'factor viii inhibidor activado por bypass *contenido proteina plasma': 'B02',
  'factor viii proteina factor ag von willebrand': 'B02',
  'factor viii recombinante': 'B02',
  'factor viii recombinante pegilado': 'B02',
  'factor von willebrand': 'B02',
  'factor von willebrand humano': 'B02',
  'factor x': 'B02',
  'factor x coagulacion entre': 'B02',
  'factor xiii plasma humano': 'B02',
  'famotidina': 'A02',
  'faricimab': 'S01',
  'febuxostat': 'M04',
  'fenazopiridina hcl': 'G04',
  'fenilalanina': 'B05',
  'fenilazopiridina': 'G04',
  'fenilbutirato glicerol': 'A16',
  'fenilefrina': 'R06',
  'fenilefrina hcl': 'N02',
  'fenilefrina microgranulos': 'R06',
  'fenilefrina microgranulos**': 'R01',
  'fenilefrinaclorhidrato': 'M01',
  'fenitoina': 'N03',
  'fenobarbital': 'N03',
  'fenofibrato': 'C10',
  'fenol': 'R02',
  'fenoterol': 'R03',
  'fenoverina': 'A03',
  'fentanilo': 'N01',
  'fentanilo equiv fentanilo': 'N01',
  'fentanilo equivelente fentanilo': 'N02',
  'fenticonazol': 'G01',
  'ferrimanitol ovoalbumina': 'B03',
  'ferroso': 'B03',
  'ferroso desecado': 'A11',
  'ferroso desecado ferroso heptahidratado * corresponden hierro': 'B03',
  'ferroso equivalentes hierro': 'A11',
  'fexofenadina': 'R06',
  'fexofenadina *': 'R06',
  'fexofenadina clorhiidrato': 'R06',
  'fexofenadina hcl': 'R06',
  'fexuprazan': 'A02',
  'fibrinogeno': 'B02',
  'fibrinogeno humano': 'B02',
  'fibrinogeno humano polvo liofilizado': 'B02',
  'filgrastim': 'L03',
  'filgrastim adnr obtenido coli k': 'L03',
  'filgrastim recombinante': 'L03',
  'fimbrias tipos adsorbidas': 'J07',
  'finasterida': 'D11',
  'finasteride': 'D11',
  'finerenona': 'C03',
  'fingolimob': 'L04',
  'fingolimod': 'L04',
  'fingolimod equivalentes fingolimod': 'L04',
  'fitomenadiona': 'B02',
  'flavonoides expresados hesperidina': 'C05',
  'flavonoides expresados hesperidina purificada': 'C05',
  'flavoxato': 'G04',
  'flavoxato clohidrato': 'G04',
  'floruro sodioequivalentea cap fluor': 'A11',
  'flubendazol': 'P02',
  'flubendazolmicronizado': 'P02',
  'flucitosina': 'J02',
  'flucocinolona acetonido': 'D07',
  'fluconazol': 'J02',
  'fluconazol*': 'J02',
  'fludarabina': 'L01',
  'fludrocortisona': 'H02',
  'flumazenil': 'V03',
  'flunarizina': 'N07',
  'fluocinolona acetonida': 'D07',
  'fluocinolona acetonido': 'S02',
  'fluor': 'A11',
  'fluoresceina': 'S01',
  'fluorometolona': 'S01',
  'fluorometolona esteril': 'S01',
  'fluorouracil': 'L01',
  'fluorouracilo': 'L01',
  'fluoruro': 'A11',
  'fluoxetina': 'N06',
  'flurbiprofeno': 'M01',
  'flutamida': 'L02',
  'fluticasona': 'R01',
  'fluticasonapropionato': 'R03',
  'fluticazona': 'R01',
  'fluvoxamina': 'N06',
  'folinato calcio equiv aacido folinico': 'V03',
  'folitropina': 'G03',
  'folitropina alfa': 'G03',
  'fondaparinux': 'B01',
  'formoterol': 'R03',
  'formoterol dihidratado': 'R03',
  'formoterol equivalentes formoterol': 'R03',
  'fosaprepitant': 'A04',
  'foscarnet triisodico hexahidratado': 'J05',
  'fosfatidilcolina disaturada acidosgrasos libres trigliceridos fosfolipidostotales': 'R07',
  'fosfatode dihidrogeno': 'B05',
  'fosfolipidos': 'R07',
  'fosfolipidos naturales': 'R07',
  'fosfolipidos totales': 'R07',
  'fosfomicina': 'J01',
  'fosforo': 'B05',
  'fostemsavir': 'J05',
  'fraccion flavonoica purificada': 'C05',
  'fraccion flavonoide purificada': 'C05',
  'fraccion flavonoide purificada correspondiente diosmina': 'C05',
  'fraccion fosfolipida pulmon': 'R07',
  'fulvestran': 'L02',
  'fulvestrant': 'L02',
  'furazolidona': 'G01',
  'furosemida': 'C03',
  'furotato mometasona': 'D07',
  'fusidato': 'D06',
  'fvw rco': 'B02',
  'gabapentin': 'N03',
  'gabapentina': 'N03',
  'gadobenato dimeglumina': 'V08',
  'gadobutrol': 'V08',
  'gadodiamida': 'V08',
  'gadoteridol': 'V08',
  'galantamina': 'N06',
  'galcanezumab': 'N02',
  'galsulfasa': 'A16',
  'ganciclovir': 'J05',
  'ganirelix': 'H01',
  'gatifloxacina': 'S01',
  'gatifloxacina sesquihidrato': 'S01',
  'gd eob dtpa sal disodica': 'V08',
  'gde glucosa': 'A07',
  'gefitinib': 'L01',
  'gel clindamicina clindamicina': 'D10',
  'gel peroxido peroxido benzoilo': 'D10',
  'gelatina succilinada': 'B05',
  'gemcitabina': 'L01',
  'gemcitabina equivalentes gencitabina': 'L01',
  'gemfibrozilo': 'C10',
  'gemigliptina': 'A10',
  'gemtuzumab ozogamicina': 'L01',
  'gentamicina': 'J01',
  'gentamicina equivalentes gentamicinabase': 'S01',
  'gentamicina gentamicina': 'J01',
  'gentamicinabase': 'S01',
  'gestodeno': 'G03',
  'gilteritinib': 'L01',
  'ginkgo biloba extracto estandarizado al': 'A11',
  'ginkgobiloba standarizado al equivalentea ginkgo flavonoides': 'N06',
  'ginseng extracto estandarizado': 'A11',
  'givosiran equivalentes givosiran': 'A16',
  'glibenclamida': 'A10',
  'glicazida': 'A10',
  'gliceril guayacolato': 'R05',
  'glicerina': 'A06',
  'glicerofosfato': 'B05',
  'glicerofosfato hidratado': 'B05',
  'glicerofosfato monohidratado': 'B05',
  'glicina': 'B05',
  'gliclazida': 'A10',
  'glicolato almidon': 'N06',
  'glicopirronio': 'R03',
  'glicosidos flavonicos': 'N06',
  'glicosidos flavonolicosde ginkgo': 'N06',
  'glimepirida': 'A10',
  'glucagon i': 'H04',
  'glucoforanosido': 'C05',
  'glucoproteina f prefusion recombinante virus sincitial respiratorio': 'J07',
  'glucoproteina virus varicela zoster antigeno geadyuvado con as b': 'J07',
  'glucosa': 'B05',
  'glucosa gcorrespondiente glucosa': 'B05',
  'glucosa glucosa': 'B05',
  'glucosa monohidrata': 'B05',
  'glucosa monohidratada': 'A07',
  'glucosaanhidra': 'V06',
  'glucosamina': 'M01',
  'glucosamina cloruro': 'M01',
  'glucosamina equivalentes aglucosamina': 'M01',
  'glucosamina glucosamina policristalino': 'M01',
  'glucosamina kcl': 'M01',
  'golimumab': 'L04',
  'gonadotropina corionica': 'G03',
  'goserelina': 'L02',
  'goserelina goserelina peptido puro': 'L02',
  'gramo diclofeno': 'M02',
  'gramos ampicilina': 'J01',
  'gramos contiene polietilenglicol': 'A06',
  'granulos metformina hcl dc': 'A10',
  'guaifenesina': 'R05',
  'guayacolato gliceril': 'R05',
  'guayacolato glicerilo': 'R05',
  'guayacolato triglicerido': 'R05',
  'guselkumab': 'L04',
  'halobetasol': 'D07',
  'haloperidol': 'N05',
  'helio': 'V03',
  'hemaglutinina b austria': 'J07',
  'hemaglutinina cepa tipo b austria': 'J07',
  'hemaglutinina cepa tipo b phuket': 'J07',
  'hemaglutinina cepa tipo missouri pdm': 'J07',
  'hemaglutinina cepa tipo singapore gp': 'J07',
  'hemaglutinina filamentosa': 'J07',
  'hemaglutinina filamentosa adsorbida': 'J07',
  'hemaglutinina filamentosa purificada adsorbida': 'J07',
  'hemaglutinina thailand': 'J07',
  'hemaglutinina victoria': 'J07',
  'hemicelulasa': 'A09',
  'hemina humana': 'B06',
  'heparina': 'B01',
  'heparina *': 'B01',
  'heparinoide': 'C05',
  'hesperidina': 'C05',
  'hexacetonido triamcinolona': 'H02',
  'hexahidrobenzoato estradiol': 'G03',
  'hialuronato': 'S01',
  'hidrobromuro dextrometorfano': 'R05',
  'hidroclorotiazida': 'C03',
  'hidrocodona': 'N02',
  'hidrocodona bitartrate': 'N02',
  'hidrocodona disesquihidrato': 'N02',
  'hidrocodona hidrato': 'N02',
  'hidrocortisona': 'H02',
  'hidrocortisona acetatoequivalente hidrocortisona': 'D07',
  'hidrocortisonabase': 'D07',
  'hidrogeno carbonato': 'A06',
  'hidromorfona': 'N02',
  'hidroquinona': 'D11',
  'hidroquinona exceso gramos': 'D11',
  'hidrosmina': 'C05',
  'hidrotalcita': 'A02',
  'hidrotalcita microfina': 'A02',
  'hidroxi metiltio butirato': 'V06',
  'hidroxi metiltiobutirato': 'B05',
  'hidroxiantraquinona': 'D01',
  'hidroxicarbamida': 'L01',
  'hidroxicina': 'N05',
  'hidroxicloroquina': 'P01',
  'hidroxido': 'B05',
  'hidroxido aluminio': 'A02',
  'hidroxido aluminio carbonato magnesio': 'A02',
  'hidroxido aluminio equivalentehidroxido aluminio': 'A02',
  'hidroxido aluminio gel carbonato magnesio': 'A02',
  'hidroxido aluminio gel humedoal': 'A02',
  'hidroxido aluminio gel seco': 'A02',
  'hidroxido aluminio gel seco al equivalentes hidroxido aluminio': 'A02',
  'hidroxido aluminiodeshidratado': 'M01',
  'hidroxido dealuminio': 'A02',
  'hidroxido magnesio': 'A02',
  'hidroxido magnesio gel humedoal': 'A02',
  'hidroxido magnesio sabor menta': 'A02',
  'hidroxido magnesio sabor original': 'A02',
  'hidroximetilendifosfonato': 'V09',
  'hidroxipropilcelulosa': 'N06',
  'hidroxipropilmetil celulosa': 'C02',
  'hidroxipropilmetilcelulosa': 'D02',
  'hidroxipropilmetilcelulosa h v': 'S01',
  'hidroxiurea': 'L01',
  'hidroxizina': 'N05',
  'hierro': 'B03',
  'hierro hierro sacarosa': 'B03',
  'hierro iii': 'B03',
  'hierro sacarosa': 'B03',
  'hioscina butil': 'N02',
  'hioscina butilbromuro': 'A03',
  'hioscina n butil': 'A03',
  'hioscina n butilbromuro': 'A03',
  'hioscina n butilromuro': 'A03',
  'hioscinan butilbromuro': 'A03',
  'hiosina metil': 'A03',
  'hipromelasa': 'N06',
  'hipromelosa': 'M01',
  'hisitidina': 'B05',
  'histidina': 'B05',
  'hydroxypropyl celulosa': 'C09',
  'i fsh i lh': 'G03',
  'i insulina': 'A10',
  'i piridoxina': 'B03',
  'i tiamina': 'B03',
  'i yoduro solucion acuosa': 'V10',
  'ibandronato': 'M05',
  'ibandronato acido libre': 'M05',
  'ibesartan': 'C09',
  'ibrutinib': 'L01',
  'ibuprofeno': 'M01',
  'ibuprofeno cd': 'M01',
  'ibuprofeno cd * equeivalente ibuprofeno': 'M01',
  'ibuprofeno cd c equivalentea ibuprofeno': 'M01',
  'ibuprofeno compresion directa': 'M03',
  'ibuprofeno compresion directaequivalentea ibuprofeno': 'M01',
  'ibuprofeno granulos dc equivalentes ibuprofeno': 'N02',
  'ibuprofeno microgranulos': 'M01',
  'ibuprofeno*': 'M01',
  'ibuprofenoensolucion': 'M01',
  'ibuprofenolisinato': 'M01',
  'icatibant': 'B06',
  'icodextrina': 'B05',
  'icosapentanoato etilo': 'C10',
  'idarubicina': 'L01',
  'idarucizumab': 'V03',
  'idursulfasa': 'A16',
  'ifosfamida': 'L01',
  'ii cianocobalamina': 'B03',
  'iloprost': 'B01',
  'iloprost trometamolequivalentea iloprost': 'B01',
  'imatinib': 'L01',
  'imidafenacina': 'G04',
  'imiglucerasa': 'A16',
  'imipenem': 'J01',
  'imipenen monohidratoequivalente imipenen': 'J01',
  'imipinem gequivalentes imipenem': 'J01',
  'imipramina': 'N06',
  'imiquimod': 'D06',
  'inclisiran': 'C10',
  'indacaterol': 'R03',
  'indapamida': 'C03',
  'indapamina': 'C09',
  'indometacina': 'M01',
  'inebilizumab': 'L04',
  'infliximab': 'L04',
  'inhibidor alfa proteinasa': 'B02',
  'inhibidor alfa proteinasa humano': 'B02',
  'inmunoglobulina': 'J06',
  'inmunoglobulina conejo antitimocitos humanos': 'L04',
  'inmunoglobulina humana anti d': 'J06',
  'inmunoglobulina humana normal': 'J06',
  'inmunoglobulina humanavirus inactivada': 'J06',
  'inmunoglobulina m': 'J06',
  'inmunoglobulinas especificas neutralizantes veneno genero bothrops': 'J06',
  'inmunoglobulinas especificas neutralizantes veneno genero crotalus': 'J06',
  'inotersen': 'N07',
  'inotuzumab ozogamicina': 'L01',
  'insulina': 'A10',
  'insulina asparta': 'A10',
  'insulina degludec': 'A10',
  'insulina detemir nmol': 'A10',
  'insulina glargina': 'A10',
  'insulina humana': 'A10',
  'insulina humana dna r': 'A10',
  'insulina humana isofana': 'A10',
  'insulina humana recombi nanate': 'A10',
  'insulina lispro unidades': 'A10',
  'insulinadegludec': 'A10',
  'interferon b': 'L03',
  'interferon beta': 'L03',
  'interferon beta b': 'L03',
  'interferon humano recombinante gamma b': 'L03',
  'intra granular dalfampridina': 'N07',
  'intragranular clobazam': 'N05',
  'intragranular efavirenz': 'J05',
  'iobenguane * radioactividad calibradaa fecha referencia': 'V09',
  'iobenguane *radioactividad calibrada fecha referencia': 'V10',
  'iodixanol': 'V08',
  'iodo': 'V08',
  'ioduro entre mbq hasta': 'V10',
  'ioduro sodioi': 'V09',
  'iohexol': 'V08',
  'iomeprol': 'V08',
  'ion calcio': 'A12',
  'ion magnesio': 'A12',
  'iopramida': 'V08',
  'iopromida': 'V08',
  'ioversol': 'V08',
  'ioversol equivalentea yodo': 'V08',
  'ipilimumab': 'L01',
  'ipratropio': 'R03',
  'irbersartan': 'C09',
  'irbesartan': 'C09',
  'irinotecan': 'L01',
  'irinotecan trihidratado': 'L01',
  'isavuconazol': 'J02',
  'isoconazol': 'G01',
  'isoconazol m': 'D07',
  'isoflavona': 'A12',
  'isoflavona soya aisladas al': 'G02',
  'isoflavonas soya': 'A12',
  'isoflavonas soya al equivalentes isoflavonas activas': 'A12',
  'isoflavonas totales': 'G02',
  'isoflurano': 'N01',
  'isoleucina': 'B05',
  'isometepteno': 'N02',
  'isometepteno equivalentes isometepteno': 'N02',
  'isometepteno mucato': 'N02',
  'isoniazida': 'J04',
  'isopropanol': 'D08',
  'isoproterenol': 'C01',
  'isosorbida dinitrato': 'C01',
  'isotretinoina': 'D10',
  'ispaghula husk': 'A06',
  'itoprida': 'A03',
  'itopride': 'A03',
  'itraconazol': 'J02',
  'itraconazol microgranulos': 'J02',
  'itraconazol microgranulos equivalentes itraconazol': 'J02',
  'itraconazol microgranulos* mgequivalentes itraconazol': 'J02',
  'ivabradina': 'C01',
  'ivabradina equivalentes ivabradina': 'C01',
  'ivermecitina': 'P02',
  'ivermectina': 'P02',
  'ixabepilona': 'L01',
  'ixazomib equivalentes ixazomib': 'L01',
  'ixekizumab': 'L04',
  'jeringa prellenada con contiene jeringa prellenada piridoxina': 'M01',
  'jeringa prellenada lidocaina': 'M01',
  'jeringa prellenada tiamina': 'M01',
  'ketamina': 'N01',
  'ketoconazol': 'D01',
  'ketoprofeno': 'M01',
  'ketoprofeno libre pirogenos': 'M01',
  'ketorolaco': 'M01',
  'ketorolaco trometamina': 'M01',
  'ketorolaco trometamina apirogena': 'M01',
  'ketorolacodetrometamina': 'S01',
  'ketorolacotrometamina': 'S01',
  'ketotifeno': 'S01',
  'ketotifeno equivalentes ketotifeno': 'R06',
  'labetalol': 'C07',
  'lacosamida': 'N03',
  'lacosamide': 'N03',
  'lactobacillus acidophilus minimo': 'G01',
  'lactobacillus acidophilusminimo': 'G01',
  'lactobacillus delbrueckii subsp bulgaricus minimo': 'G01',
  'lactobacillus lb cepa lacteol demediode cultivo fermentado*': 'A07',
  'lactobacillus paracasei minimo': 'G01',
  'lactobacillus plantarum minimo': 'G01',
  'lactobacillus plantarumminimo': 'G01',
  'lactosa': 'C09',
  'lactulosa': 'A06',
  'lamivudina': 'J05',
  'lamotrigina': 'N03',
  'lanadelumab': 'B06',
  'lanreotida': 'H01',
  'lanreotida equivamente lanreotida': 'H01',
  'lanreotide': 'H01',
  'lansoprazol': 'A02',
  'lansoprazol microgranulos': 'A02',
  'lansoprazol microgranulos con cubierta enterica una potencia equivalentes lansoprazol': 'A02',
  'lansoprazol microgranulos gastrorresistentes': 'A02',
  'lansoprazol pellets equivalentes lansoprazol': 'A02',
  'lapatinib': 'L01',
  'laronidasa': 'A16',
  'larotrectinib': 'L01',
  'larotrectinib equivalentes larotrectinib': 'L01',
  'latanoprost': 'S01',
  'lebrikizumab': 'D11',
  'leflunomida': 'L04',
  'lenalidomida': 'L04',
  'lenalidomida amonio cloruro cocristal equivalentes lenalidomida': 'L04',
  'lenvatinib': 'L01',
  'lenvatinib libre': 'L01',
  'letermovir': 'J05',
  'letrozol': 'L02',
  'leucina': 'B05',
  'leuprolide': 'L02',
  'levadura con selenio': 'A11',
  'levetiracetam': 'N03',
  'levetiracetam solucion inyectble': 'N03',
  'levo amlodipino': 'C09',
  'levo amlodipino nicotinato levo amlodipino': 'C09',
  'levoamlodipino': 'C08',
  'levobupivacaina': 'N01',
  'levocarnitina': 'A16',
  'levocetiricina': 'R06',
  'levocetirizina': 'R06',
  'levocetirizinadiclorhidrato': 'R01',
  'levocetirizinadihidrocloruro': 'R03',
  'levocloperastina': 'R05',
  'levodopa': 'N04',
  'levodropropizina': 'R05',
  'levofloxacina': 'J01',
  'levofloxacina equivalentes levofloxacina': 'J01',
  'levofloxacino': 'J01',
  'levofloxacino equivalentes levofloxacino': 'J01',
  'levomepromazina': 'N05',
  'levomepromazinabase': 'N05',
  'levonorgestrel': 'G03',
  'levosimendan': 'C01',
  'levosulpirida': 'A09',
  'levosulpiride': 'A09',
  'levotiroxina': 'H03',
  'levotiroxina *': 'H03',
  'levotiroxina pentahidratada': 'H03',
  'levotiroxinasodica': 'H03',
  'levulinato calcio': 'A12',
  'levulinato calcio dihidratado': 'A12',
  'libera rotigotina horas contiene rotigotina': 'N04',
  'lidocaina': 'N01',
  'lidocaina clorhidarto': 'S03',
  'lidocaina hc': 'S01',
  'lidocaina s p': 'N01',
  'linagliptina': 'A10',
  'lincomicina': 'J01',
  'lincomicina clorhidratomonohidrato equivalentea lincomicinabase': 'J01',
  'lincomicina equivalentes lincomicina': 'J01',
  'linezolid': 'J01',
  'linezolida': 'J01',
  'liofilizado contiene inhibidor estearasa c': 'B06',
  'liraglutida': 'A10',
  'lisado liofilizado coli *': 'G04',
  'lisados bacterianos liofilizados haemophilus influenzae streptococcus pneumoniae klebsiella pneumoniae ssp pneumoniae ssp ozaenae staphylococcus aureus streptococcus pyogenes sanguinis moraxella catarrhalis': 'R07',
  'lisdexanfetamina dimesilato': 'N06',
  'lisdexanfetaminadimesilato': 'N06',
  'lisina': 'B05',
  'lisina monoacetato': 'B05',
  'lisinopril': 'C09',
  'lisinopril equivalentes alisinopril': 'C09',
  'lisinopril mgequivalentealisinopril': 'C09',
  'lixisenatida': 'A10',
  'lomitapida': 'C10',
  'lomitapida equivalentes lomitapida': 'C10',
  'lomitapide': 'C10',
  'loperamida': 'A07',
  'loperamidaclorhidrato': 'A07',
  'lopinavir': 'J05',
  'loratadina': 'R06',
  'lorazepam': 'N05',
  'lorlatinib': 'L01',
  'losartan': 'C09',
  'losartanpotasico': 'C09',
  'loteprednol etabonato': 'S01',
  'loteprednol etabonato esteril': 'S01',
  'lovastatina': 'C10',
  'loxoprofen': 'M01',
  'lubiprostona': 'A06',
  'lubiprostone': 'A06',
  'lumefantrina': 'P01',
  'lumenfantrina': 'P01',
  'lurasidona': 'N05',
  'lurasidona hcl': 'N05',
  'luspatercept': 'B03',
  'lutecio cloruro': 'V10',
  'lutropina alfa': 'G03',
  'm etabisulfito': 'N02',
  'macitentan': 'C02',
  'macroagregados albumina humana plasmatica': 'V09',
  'macrogol': 'A06',
  'macrogol peg': 'N06',
  'magaldrato': 'A02',
  'magaldrato al': 'A02',
  'magnesio': 'N06',
  'magnesio clorurohexadihidratado': 'B05',
  'magnesio h': 'B05',
  'magnesio heptahidratado': 'A06',
  'magnesio hidroxido': 'A02',
  'magnesio tetrahidrato': 'B05',
  'manganeso': 'A11',
  'manitol': 'N06',
  'maraviroc': 'J05',
  'maribavir': 'J05',
  'materiales intragranulares finasterida': 'G04',
  'materiales intragranulares palbociclib': 'L01',
  'mavacamten': 'C01',
  'mebendazol': 'P02',
  'mebeverina': 'A03',
  'mebrofenina': 'V09',
  'mecasermina': 'H01',
  'meclizina': 'R06',
  'medroxiprogesterona': 'G03',
  'megestrol': 'L02',
  'meglumina diatrizoato': 'V08',
  'melatonina': 'N05',
  'melfalan': 'L01',
  'melfalan equivanete melfalan': 'L01',
  'meloxicam': 'M01',
  'meloxican': 'M01',
  'memantina': 'N06',
  'memantina hcl': 'N06',
  'menotropina': 'G03',
  'mentol': 'C01',
  'mentol cristal': 'M02',
  'mentol cristales': 'D02',
  'mentol levorotatorio': 'D11',
  'meperidina': 'N02',
  'mepivacaina': 'N01',
  'mepivacainaclorhidrato': 'N01',
  'mepolizumab': 'R03',
  'mercaptopurina': 'L01',
  'meropenem': 'J01',
  'meropenem trihidratado': 'J01',
  'mertiatida': 'V09',
  'mesalazina': 'A07',
  'mesna': 'V03',
  'metadona': 'N07',
  'metadoxina': 'N07',
  'metamizol': 'N02',
  'metformina': 'A10',
  'metformina dc *': 'A10',
  'metformina hcl': 'A10',
  'metforminaclorhidrato': 'A10',
  'metforminaclorhidrato granuladoc d equivalenteametforminaclorhidrato**': 'A10',
  'metil oxi': 'B05',
  'metil oxi butirato': 'B05',
  'metil oxobutarato': 'V06',
  'metil oxovalerato': 'V06',
  'metildopa': 'C02',
  'metilfenidato': 'N06',
  'metilprednisolona': 'H02',
  'metilprednisolona aceponato': 'D07',
  'metilprednisolona esteril': 'H02',
  'metilsulfonil metano': 'M01',
  'metilsulfonilmetano': 'M01',
  'metimazol': 'H03',
  'metionina': 'B05',
  'metisoprinol': 'J05',
  'metocarbamol': 'M03',
  'metoclopramida': 'A03',
  'metoclopramida monohidratado': 'A03',
  'metopirone contiene metirapona': 'V04',
  'metoprolol': 'C07',
  'metotrexate': 'L01',
  'metotrexato': 'L04',
  'metotrexatobase': 'L04',
  'metoxalem': 'D05',
  'metoxiflurano': 'N01',
  'metoxipolietilenglicol epoetina beta': 'B03',
  'metronidazol': 'P01',
  'metronidazol benzoil': 'G01',
  'metronidazol benzoil metronidazol': 'A01',
  'metronidazolbase': 'P01',
  'metronidazolmicronizado': 'G01',
  'mexazolam': 'N05',
  'mezcla aceite oliva aceite soya': 'B05',
  'mezcla natural que contiene oxigeno': 'V03',
  'mezcla seco metformina': 'A10',
  'mgde epa dha': 'C10',
  'micofenolato equivalenteaacido micofenolico': 'L04',
  'micofenolato mofetilo': 'L04',
  'miconazol': 'G01',
  'microganulos omeprazol al equivalentes omeprazol': 'A02',
  'microgramos peptido neto': 'V09',
  'microgranulos acido ascorbico que contienen acido ascorbico': 'B03',
  'microgranulos acido folico que contienen acido folico': 'B03',
  'microgranulos cafeinaequivalentes cafeina': 'M01',
  'microgranulos ferroso equivalentes ferroso': 'B03',
  'microgranulos ferroso que contienen ferroso': 'B03',
  'microgranulos gastroresistentes esomeprazol': 'A02',
  'microgranulos ibuprofeno equivalentes ibuprofeno': 'M01',
  'microgranulos liberacion prolongada diclofenaco': 'M01',
  'microgranulos multivitaminico equivalentes acido ascorbico': 'B03',
  'microgranulos omeprazol al w w equivalentes ade omeprazol': 'A02',
  'midazolam': 'N05',
  'midodrina': 'C01',
  'midostaurina': 'L01',
  'mifamurtida': 'L03',
  'mifepristona': 'G03',
  'migalastat': 'A16',
  'miglustat': 'A16',
  'mililitro contiene insulina glarginaque correspondena insulina glargina': 'A10',
  'milrinona': 'C01',
  'miltefosina': 'L01',
  'minitabletas cubiertas gastroresistentesde fenofibrato colina equivalentea acido fenofibrico': 'C10',
  'minitabletas telmisartan cubiertas equivalentes telmisartan': 'C09',
  'minociclina': 'J01',
  'minoxidil': 'D11',
  'minoxidil locion': 'D11',
  'minoxidil solucion topica': 'D11',
  'mirabegron': 'G04',
  'mirikizumab': 'L04',
  'mirtazapina': 'N06',
  'misoprostol': 'G02',
  'missouri pdm cepa analoga': 'J07',
  'mitomicina c': 'L01',
  'mitotano': 'L01',
  'mitoxantrona': 'L01',
  'mo molibdato gbq fecha hora referencia actividad': 'V09',
  'modafinil': 'N06',
  'molibdato': 'A11',
  'molibdato dia calibraciony pernectato variable basada actividad molibdeno mo': 'V09',
  'molibdato dihidratado': 'B05',
  'molibdato fecha referencia': 'V09',
  'molibdeno': 'A11',
  'molibdeno molibdato gbq fecha calibracion': 'V09',
  'molibdeno molibdato gbq fecha referencia': 'V09',
  'molibdeno tecnecio entreun rango gbq gbq': 'V09',
  'mometasona': 'D07',
  'mometasona w w': 'R01',
  'mometasonaanhidra': 'D05',
  'monoacetato lisina': 'B05',
  'monobasico': 'A06',
  'monohidratado': 'A07',
  'mononitrato tiamina': 'B05',
  'montelukast': 'R03',
  'montelukast equiv montelukast': 'R03',
  'montelukast equivalentea montelukas': 'R03',
  'montelukast monosodico': 'R03',
  'montelukast sodicoequivalente montelukast libre': 'R03',
  'morfina': 'N02',
  'moroctocog alfa': 'B02',
  'mosaprida': 'A03',
  'moxicilina': 'J01',
  'moxifloxacina': 'J01',
  'moxifloxacina equivalentes moxifloxacina': 'S01',
  'moxifloxacinabase': 'S01',
  'moxifloxacino': 'J01',
  'moxifloxacino*': 'S01',
  'moxifloxacinobase': 'S03',
  'mpicilina': 'J01',
  'msm': 'M01',
  'mtc pertecnetato gbq fecha hora referencia actividad': 'V09',
  'mucato isometepteno': 'N02',
  'mupirocina': 'D06',
  'mycobacterium bovis bcg cepa danesa viva atenuada': 'L03',
  'n acetil cisteina': 'R05',
  'n acetil tirosina': 'B05',
  'n acetilcisteina': 'R05',
  'n butil hioscina': 'A03',
  'n butilbromuro escopolamina': 'A03',
  'n butilbromuro hioscina': 'A03',
  'n butilbromuro hiosina': 'M01',
  'nadroparina': 'B01',
  'nadroparina anti axa': 'B01',
  'nafazolina': 'S01',
  'naloxona': 'V03',
  'naltrexona': 'N07',
  'nanocoloide albumina serica humana': 'V09',
  'nanogramos calculados radio fecha referencia': 'V10',
  'naproxeno': 'M01',
  'naproxeno equivalentede naproxeno': 'M01',
  'naproxeno equivalentes naproxeno': 'N02',
  'naproxenobasecon deexceso': 'M01',
  'naratriptan': 'N02',
  'natalizumab': 'L04',
  'nebivolol': 'C07',
  'nefopam': 'N02',
  'neomicina': 'S01',
  'neomicina ***': 'D07',
  'neomicina eq neomicina': 'D07',
  'neomicinasulfato': 'D07',
  'neomicinasulfato equivalenteaneomicinabase': 'D07',
  'neostigmina metil': 'N07',
  'neostigmina metilsulfato': 'N07',
  'neostigminametilsulfato': 'N07',
  'nepafenaco': 'S01',
  'neratiniib': 'L01',
  'nevirapina equivamente nevirapina': 'J05',
  'niacinamida': 'A11',
  'niclosamida': 'P02',
  'nicotina': 'N07',
  'nicotinamida': 'A11',
  'nicotinamida acido ascorbico': 'A11',
  'nicotinamida ascorbato': 'A11',
  'nifedipina': 'C08',
  'nifedipino': 'C08',
  'nifuroxazida': 'A01',
  'nifuroxazide': 'P01',
  'nifurtimox': 'P01',
  'nilotinib': 'L01',
  'nimesulida': 'M01',
  'nimodipino': 'C08',
  'nintedanib': 'L01',
  'niraparib': 'L01',
  'niservimab': 'J06',
  'nistatina': 'D01',
  'nistatina equivalentes': 'A07',
  'nistatina und': 'G01',
  'nistatinaui': 'D01',
  'nitaxozanida': 'P01',
  'nitazoxamida': 'P01',
  'nitazoxanida': 'P01',
  'nitisinona': 'A16',
  'nitrofurantoina': 'J01',
  'nitrofurantoina macrocristales': 'J01',
  'nitrofurazona': 'D08',
  'nitrogeno c s': 'V03',
  'nitroglicerina': 'C01',
  'nitroglicerinaen dextrosaal': 'C01',
  'nitroprusiato': 'C02',
  'nivolumab': 'L01',
  'nomegestrol': 'G03',
  'norepinefrina': 'C01',
  'noretindrona': 'G03',
  'noretisterona': 'G03',
  'norfloxacina': 'J01',
  'norfloxacino': 'J01',
  'norfloxacino exceso': 'J01',
  'noscapina': 'R03',
  'nucleo acetaminofen': 'N02',
  'nucleo diclofenaco': 'M01',
  'nucleo entacapona': 'N04',
  'nucleo fase intragranular abiraterona': 'L02',
  'nucleo ibuprofeno': 'M01',
  'nucleo verapamilo': 'C08',
  'nucleo* rufinamida': 'N03',
  'nusinersen': 'M09',
  'obinutuzumab': 'L01',
  'ocrelizumab': 'L04',
  'octreotida': 'H01',
  'octreotidabase': 'H01',
  'ofatumumab': 'L01',
  'olanzapina': 'N05',
  'olaparib': 'L01',
  'oligosacarido meningococico grupo c gconjugado con proteina crm corynebacterium diphtheriae': 'J07',
  'oligosacarido meningococico grupo conjugado con proteina crm corynebacterium diphtheriae': 'J07',
  'oligosacarido meningococico grupo w conjugado con proteina crm corynebacterium diphtheriae': 'J07',
  'oliosido salmonella typhi': 'J07',
  'olipudasa alfa': 'A16',
  'olmesartam medoxomil': 'C09',
  'olmesartan': 'C09',
  'olmesartan medoxomil': 'C09',
  'olmesartan medoxomilo': 'C09',
  'olmesartan medoxomilo hidroclorotiazida': 'C09',
  'olmesartanmedoxomil': 'C09',
  'olmesartn medoxomilo': 'C09',
  'olodaterol': 'R03',
  'olopatadina': 'S01',
  'omalizumab': 'R03',
  'omepazol': 'A02',
  'omeprazol': 'A02',
  'omeprazol equivalentea omeprazol': 'A02',
  'omeprazol equivalentes omeprazol': 'A02',
  'omeprazol microgranulos': 'A02',
  'omeprazol microgranulos equivalentes omeprazol': 'A02',
  'omeprazol omeprazol': 'A02',
  'omeprazol pellets': 'A02',
  'omeprazol pellets al equivalentea omeprazol': 'A02',
  'omeprazol pellets equivalentes omeprazol': 'A02',
  'omeprazolbase': 'A02',
  'omv': 'J07',
  'onasemnogen abeparvovec': 'M09',
  'ondansetron': 'A04',
  'ondasetron': 'A04',
  'opadry b rojo': 'N06',
  'opadry b rosado': 'N06',
  'orlistat': 'A08',
  'orlistat pellets equivalentes orlistat': 'A08',
  'ornitina': 'B05',
  'ornitina aspartato': 'A05',
  'oseltamivir': 'J05',
  'osilodrostat': 'H02',
  'osimertinib equivalentes osimertinib': 'L01',
  'otilonio': 'A03',
  'oxacilina': 'J01',
  'oxacilina eq oxacilina': 'J01',
  'oxaliplatino': 'L01',
  'oxantel': 'P02',
  'oxantel equivalentea oxantel': 'P02',
  'oxaprozina': 'M01',
  'oxcarbazepina': 'N03',
  'oxibutina': 'G04',
  'oxibutinina': 'G04',
  'oxibutinina cloruro': 'G04',
  'oxibutinina hcl': 'G04',
  'oxibutinino cloruro': 'G04',
  'oxicodona': 'N02',
  'oxido aluminio': 'V09',
  'oxido hierro': 'D02',
  'oxido hierro rojo': 'N06',
  'oxido magnesio ligero': 'A06',
  'oxido magnesio liviano': 'A06',
  'oxido magnesio pesado': 'A11',
  'oxido nitrico': 'R07',
  'oxido nitrico ppm': 'R07',
  'oxido nitroso': 'N01',
  'oxido nitroso medicinal': 'N01',
  'oxido zinc': 'C05',
  'oxido zinc equivalentes zinc': 'A11',
  'oxidode zinc': 'D02',
  'oxidronato': 'V09',
  'oxigeno': 'V03',
  'oxigeno activo al v v': 'V03',
  'oxigeno gaseoso': 'V03',
  'oxigeno gaseoso medicinal pureza m oxigeno gaseoso cilindro alta presion equivale oxigeno gaseoso litro oxigeno liquido almacenado contenedores criogenicos equivale litros oxigeno ga': 'V03',
  'oxigeno gaseoso obtenido por metodo criogenico': 'V03',
  'oxigeno medicinal': 'V03',
  'oxigeno medicinal liquido': 'V03',
  'oxigeno no menos': 'V03',
  'oxigeno no menos volumen total': 'V03',
  'oxigeno v v producido envasado por metodo psa': 'V03',
  'oximetazolina': 'R01',
  'oximetazolina hcl': 'R01',
  'oximetazolinaclorhidrato': 'R01',
  'oxipurina': 'A05',
  'oxitetraciclina': 'S01',
  'oxitocina': 'H01',
  'oxitocina con actividad media corresponde': 'H01',
  'oxitocina sintetica': 'H01',
  'oxo fenil acido propionico': 'B05',
  'oxo fenilpropionato': 'V06',
  'paclitaxel': 'L01',
  'paclitaxel ligado albumina': 'L01',
  'paclitaxel nano particulas': 'L01',
  'paclitaxel solucion inyectable': 'L01',
  'palbociclib': 'L01',
  'paliperidona': 'N05',
  'paliperidona equivalentes paliperidona': 'N05',
  'palivizumab': 'J06',
  'palonosetron': 'A04',
  'pancreatina': 'A09',
  'pancreatina correspondiente amilasa lipasa proteasas totales': 'A09',
  'pancreatina cual contiene ph eur amilasa ph eur lipasa ph eur proteasa': 'A09',
  'pancreatina nf': 'A09',
  'pancreatina x nf': 'A09',
  'pancuronio': 'M03',
  'panitumumab': 'L01',
  'pantetonato calcio': 'A11',
  'pantoprazol': 'A02',
  'pantoprazol sesquihidrato': 'A02',
  'pantotenato': 'B05',
  'pantotenato calcio': 'A11',
  'papaina': 'M09',
  'papaverina': 'G04',
  'paracetamol': 'N02',
  'paracetamol cd equivalentes paracetamol': 'N02',
  'paracetamol composicion paracetamol dc paracetamol almidon pregelatinizado povidona almidon glicolato metilparabeno propilparabeno acido estearico': 'N02',
  'paracetamol dc equivalentes paracetamol*': 'N02',
  'parafina': 'N01',
  'parecoxib': 'M01',
  'pargeverina': 'A03',
  'paricalcitol': 'H05',
  'paroxetina': 'N06',
  'paroxetina equivalentes paroxetina': 'N06',
  'paroxetinabase': 'N06',
  'pasireotida': 'H01',
  'pazopanib': 'L01',
  'pectina': 'A07',
  'pegaspargasa': 'L01',
  'pegcetacoplan': 'S01',
  'pegfilgrastim': 'L03',
  'pegfilgrastim factor estimulante colonias granulocitos humano recombinante pegilado': 'L03',
  'peginterferon beta': 'L03',
  'pegunigalsidasa alfa': 'A16',
  'pegvisomant': 'H01',
  'pelicula recubrimiento con medicamento metilfenidato': 'N06',
  'pelicula recubrimiento metilfenidato': 'N06',
  'pelles que corresponden esomeprasol': 'A02',
  'pellets esomeprazol al equivalentes esomeprazol': 'A02',
  'pellets esomeprazol con cubierta enterica equivalentes esomeprazol': 'A02',
  'pembrolizumab': 'L01',
  'pemetrexed': 'L01',
  'pemetrexed acido libre': 'L01',
  'pemetrexed disodico heptahidratado': 'L01',
  'pemetrexed disodico heptahidratado equivalentea pemetrexed': 'L01',
  'penciclovir': 'D06',
  'pencilina': 'J01',
  'penicilina': 'J01',
  'penicilina benzatinica': 'J01',
  'penicilina penicilina benzatinica': 'J01',
  'penicilina procaina': 'J01',
  'penicilina v': 'J01',
  'pentetato calcio trisodico': 'V09',
  'pentosan polisulfato': 'G04',
  'pentoxifilina': 'C04',
  'perindopril arginato correspondiente perindopril': 'C09',
  'perindopril arginato correspondiente perindropril': 'C09',
  'perindopril arginina': 'C09',
  'perindopril arninina corresponde perindopril': 'C09',
  'perindopril que corresponden perindopril arginina': 'C09',
  'permetrina': 'P03',
  'peroxido benzoilo': 'D10',
  'peroxido benzoilo hidratado': 'D10',
  'peroxido carbamida': 'D02',
  'peroxido debenzoilohidratadoequivalenteaperoxidodebenzoiloanhidro': 'D10',
  'peroxido dehidrogrenoal gequivalentes volumenes': 'D08',
  'peroxido hdrogeno': 'D08',
  'peroxido hidrogeno': 'D08',
  'peroxido hidrogeno al': 'D08',
  'peroxido hidrogeno p p': 'D08',
  'pertactina': 'J07',
  'pertactina adsorbida': 'J07',
  'pertecnetato': 'V09',
  'pertecnetato fecha referencia': 'V09',
  'pertuzumab': 'L01',
  'petrolato blanco': 'D02',
  'picosulfato': 'A06',
  'picosulfato sodicomonohidrato': 'A06',
  'picosulfatode': 'A06',
  'pidotimod': 'L03',
  'pilocarpina': 'N07',
  'pinaverio': 'A03',
  'piperaciclina': 'J01',
  'piperacilina': 'J01',
  'piperacilina gramos equivalentes pipelacilina': 'J01',
  'piperacilina sodicaequivalentes pipelacilina': 'J01',
  'piperacilina tazobactam': 'J01',
  'piperacilinabase': 'J01',
  'pipotiazina': 'N05',
  'piracetam': 'N06',
  'pirantel': 'P02',
  'pirantel pirantel': 'P02',
  'pirantelbase': 'P02',
  'pirazinamida': 'J04',
  'pirfenidona': 'L04',
  'piridostigmina': 'N07',
  'piridoxina': 'A11',
  'piridoxina clohidrato': 'A11',
  'pirimetamina': 'P01',
  'piritinol': 'N06',
  'piritinol diclorhidratro': 'N06',
  'pirofosfato decahidratado': 'V09',
  'piroxicam': 'M01',
  'piroxicam polvo': 'M02',
  'piroxidina': 'A11',
  'pitavastatina': 'C10',
  'plerixafor': 'L03',
  'podofilina': 'D06',
  'podofilina hexandrum': 'D06',
  'poilimixina b equivaelente polimixina b': 'S01',
  'polatuzumab vedotina': 'L01',
  'policresuleno': 'G01',
  'polidocanol': 'C05',
  'poliestireno sulfonato calcio': 'V03',
  'polietilenglicol': 'A06',
  'polietilenglicol nf': 'S01',
  'polimicina b': 'S01',
  'polimixima b': 'S01',
  'polimixina': 'S01',
  'polimixina b': 'J01',
  'polimixina b esteril equivaelente polimixina b': 'S01',
  'poliovirus inactivado tipo': 'J07',
  'polisacarido capsular haemophilus influenzae tipo b conjugado con toxoide tetanico aproximadamente': 'J07',
  'polisacarido capsular purificado meningococo serogrupo c': 'J07',
  'polisacarido haemophilus influenzae tipo b': 'J07',
  'polisacarido haemophilus influenzae tipo b combinado proteina tetanica': 'J07',
  'polisacarido neisseria meningitidis grupo **conjugados con proteina transportadora toxoide tetanico': 'J07',
  'polisacarido neisseria meningitidisgrupo *': 'J07',
  'polisacarido neisseria meningitidisgrupo c*': 'J07',
  'polisacarido neisseria meningitidisgrupo w *': 'J07',
  'polisacarido serotipo': 'J07',
  'polisacarido serotipo b': 'J07',
  'polisacarido serotipo c': 'J07',
  'polisacarido serotipo f': 'J07',
  'polisacarido serotipo neumococico': 'J07',
  'polisacarido serotipo neumococico c': 'J07',
  'polisacarido serotipo neumococico f': 'J07',
  'polisacarido serotipo neumococico serotipo b': 'J07',
  'polisacarido serotipo neumococico v': 'J07',
  'polisacarido serotipo v': 'J07',
  'polisacaridos purificados capsulares streptococcus pneumoniae tipo': 'J07',
  'polisorbato': 'C02',
  'polivinilpirrolidona': 'S01',
  'polvo esteril para reconstituir asuspensioninyectable equivalentes penicilina benzatinica': 'J01',
  'pomalidomida': 'L04',
  'ponatinib equivalentes ponatinib': 'L01',
  'por': 'R03',
  'posaconazol': 'J02',
  'potasiomonohidratado': 'A07',
  'povidona': 'L04',
  'povidona yodada': 'D08',
  'ppm cloro': 'D08',
  'pralatrexato': 'L01',
  'pralidoxima': 'V03',
  'pramipexol': 'N04',
  'pramipexol dihidrocloruro': 'N04',
  'pramipexol libre': 'N04',
  'pramoxina': 'D04',
  'prasugrel': 'B01',
  'pravastatina': 'C10',
  'praziquantel': 'P02',
  'prazosina': 'C02',
  'prdnisolona': 'S01',
  'predispensada contiene microgramos umeclidinio esto equivale una administrada microgramos umeclidinio': 'R03',
  'prednicarbato': 'D07',
  'prednisolona': 'H02',
  'prednisona': 'H02',
  'pregabalina': 'N03',
  'pregabalina tabletas': 'N03',
  'prilocaina': 'N01',
  'primaquina': 'P01',
  'primidona': 'N03',
  'probiotics x ufc sachet': 'A07',
  'procaina': 'N01',
  'procianidinas': 'C05',
  'progesterona': 'G03',
  'prolina': 'B05',
  'promestrieno': 'G03',
  'propafenona': 'C01',
  'propanolol': 'C07',
  'proparacaina': 'S01',
  'propianato fluticasona': 'R03',
  'propilenglicol': 'S01',
  'propiltiouracilo': 'H03',
  'propinox': 'A03',
  'propofol': 'N01',
  'propranolol': 'C07',
  'protamina': 'V03',
  'proteina c': 'B02',
  'proteina c entre': 'B02',
  'proteina factor ag von willebrand': 'B02',
  'proteina humana > distribucion las subclases igg igg igg igg igg contenido maximo iga es': 'J06',
  'proteina humana con inmunoglobulina humana normal': 'J06',
  'proteina humana cual por lo menos es igg con un contenido anticuerpos contra antigeno superficie virus hepatitis b': 'J06',
  'proteina humana cual por lo menos es igg con un contenidode anticuerpos contra antigeno superficie virus hepatitis b': 'J06',
  'proteina humana las cuales contiene al menos inmunoglobulinas con anticuerpos contra antigenos hbs no menos': 'J06',
  'proteina li vph tipo': 'J07',
  'proteina plasma humano con al menos albumina': 'B05',
  'proteina plasma humano con cantidades menores oigualesa cual contiene inmunoglobulina humanaantid cantidades mayoreso igualesa i correspondientea cantidades mayores iguales': 'J06',
  'proteina plasma humano cual albumina es minimo': 'B05',
  'proteina plasma humano mgde cual inmunoglobulina > con anticuerpos contra citomegalovirus': 'J06',
  'proteina plasmatica conalmenosun dealbuminahumana': 'B05',
  'proteina plasmatica humana con actividad contra los inhibidores factor viii': 'B02',
  'proteina plasmatica humana con actividad contra losinhibidores factor viii': 'B02',
  'proteina s': 'B02',
  'proteina s entre': 'B02',
  'proteina total cual >= es igg humana': 'J06',
  'proteina transportadora crm': 'J07',
  'proteina vph': 'J07',
  'proteina vph tipo': 'J07',
  'proteinas plasma humano': 'B05',
  'proteinas plasma humano las cuales inmunoglobulinas son al menos': 'J06',
  'proteinas plasma humano que contiene no menos inmunoglobulinas': 'J06',
  'proteinas plasmaticas con al menos un albumina humana': 'B05',
  'prucaloprida': 'A06',
  'prucaloprida mgequivalen prucalopride': 'A06',
  'pseudoefedrina': 'M02',
  'pseudoefedrina microgranulos al liberacion prolongada equivalentes pseudoefedrina': 'R01',
  'psyllium semillas': 'A06',
  'quetiapina': 'N05',
  'r asparaginasa': 'L01',
  'raltegravir': 'J05',
  'raltegravir* eq por factor sal igual x fenol libre': 'J05',
  'ramipril': 'C09',
  'ramucirumab': 'L01',
  'ranibizumab': 'S01',
  'ranitidina': 'A02',
  'ranolazina': 'C01',
  'rasagilina': 'N04',
  'rasagilina euivalente arasagilina': 'N04',
  'rasagilina rasagilina': 'N04',
  'rasburicasa': 'V03',
  'ravulizumab': 'L04',
  'raxtozinameran': 'J07',
  'recubierta rosa nomegestrol': 'G03',
  'recubrimiento ii rojo': 'L04',
  'recubrimiento opadry brown h': 'C02',
  'regorafenib': 'L01',
  'relatlimab': 'L01',
  'relebactam': 'J01',
  'remifentanil': 'N01',
  'remifentanilo': 'N01',
  'remifentanilo hcl': 'N01',
  'resorcinol': 'D10',
  'retinol': 'A11',
  'retinol correspondiente retinol': 'A11',
  'rfix factor ix coagulacion recombinante': 'B02',
  'ribaroxaban': 'B01',
  'ribociclib': 'L01',
  'riboflavina': 'A11',
  'riboflavina dihidratada': 'A11',
  'rifabutina': 'J04',
  'rifamicina': 'J04',
  'rifamicina equivalentea rifamicina': 'D06',
  'rifamicina equivalentes rifamicina': 'D06',
  'rifampicina': 'J04',
  'rifapentina': 'J04',
  'rifaximina': 'A07',
  'rifaximina polimorfo alfa': 'A07',
  'rilpirivina': 'J05',
  'rilpivirin equivalentes rilpivirin': 'J05',
  'rilpivirina': 'J05',
  'riluzol': 'N07',
  'rimegepant': 'N02',
  'riociguat': 'C02',
  'risankizumab solucion innyectable': 'L04',
  'risdiplam': 'M09',
  'risperidona': 'N05',
  'risperidona polimorfo i': 'N05',
  'ristriona': 'N05',
  'ritonavir': 'J05',
  'ritonavir **': 'J05',
  'rituximab': 'L01',
  'rivaroxaban': 'B01',
  'rivastigmina': 'N06',
  'rivastigmina con una liberacion nominal horas': 'N06',
  'rivastigmina hidrogenotartrato equivalentes arivastigminabase': 'N06',
  'rociverina': 'A03',
  'rocuronio': 'M03',
  'roflumilast': 'R03',
  'rojo # d&c': 'N02',
  'romosozumab': 'M05',
  'rosuvastatica': 'C10',
  'rosuvastatina': 'C10',
  'rosuvastatina contiene por': 'C10',
  'rosuvastatina equivalentea rosuvastatina': 'C10',
  'rosuvastatina equivalenterosuvastatina': 'C10',
  'rosuvastatina equivalentes rosuvastatina': 'C10',
  'rosuvastatina expresada rosuvastatina': 'C10',
  'rosuvastatina mgequivalente rosuvastatina': 'C10',
  'rosuvastatina rosuvastatina': 'C10',
  'rosuvastatinabase': 'C10',
  'rotavirus humano vivo atenuado no menos x ccid': 'J07',
  'rotigotina': 'N04',
  'rp c': 'J07',
  'rufinamida': 'N03',
  'ruibarbo polvo': 'A06',
  'ruibarbo polvo raiz': 'A06',
  'rupatadina': 'R06',
  'rupatadina equivalentes rupatadina': 'R06',
  'rutina': 'A11',
  'ruxolitinib': 'L01',
  's amlodipino': 'C08',
  's carboximetil cisteina': 'R05',
  's carboximetilcisteina': 'R05',
  'sabor durazno': 'B05',
  'sacarato hidroxido ferrico': 'B03',
  'saccharomyces boulardii': 'A07',
  'sacituzumab govitecan': 'L01',
  'sacubitril': 'C09',
  'sacubitril valsartan dioxido silicio coloidal sacubritil valsartan': 'C09',
  'sacubitrilo': 'C09',
  'sacubitrilo valsartan': 'C09',
  'sacubitrilo valsartran': 'C09',
  'safinamida': 'N04',
  'salbutamol': 'R03',
  'salbutamol equivalennte salbutamol': 'R03',
  'salbutamol equivalentea salbutamol': 'R03',
  'salbutamol equivalentes salbutamol': 'R03',
  'salbutamol mcgequivalente salbutamol': 'R03',
  'salbutamolbase': 'R03',
  'salbutamolsulfato': 'R03',
  'salicilanilida': 'D01',
  'salicilato dietilamina': 'C05',
  'salicilato metilo': 'D11',
  'salmeterol': 'R03',
  'salmeterol equivalentes salmeterol': 'R03',
  'satralizumab': 'D11',
  'sebelipasa alfa': 'A16',
  'secnidazol': 'P01',
  'secukinumab': 'L04',
  'selenio': 'A11',
  'selenito': 'B05',
  'selenito pentahidratado': 'B05',
  'selexipag': 'B01',
  'selpercatinib': 'L01',
  'semaglutida': 'A10',
  'sen hojas polvo': 'A06',
  'sen polvo': 'A06',
  'sen polvo hojas': 'A06',
  'senosido b*': 'A06',
  'senosidos & b potencia': 'A06',
  'senosidos &b': 'A06',
  'senosidos b mgequivalentes senosidos b': 'A06',
  'serina': 'B05',
  'serotipo recombinanteg =': 'J07',
  'serotipo recombinantep =': 'J07',
  'serotipo virus dengue': 'J07',
  'serotipo virus dengue vivo atenuado': 'J07',
  'sertaconazol': 'D01',
  'sertralina': 'N06',
  'sertralina equiv sertralina': 'N06',
  'sertralina equivalentes sertralina': 'N06',
  'sertralinaclorhidrato equivalentes': 'N06',
  'sevelamer': 'V03',
  'sevelamero carbonato': 'V03',
  'sevoflurano': 'N01',
  'sildenafil': 'G04',
  'sildenafilbase': 'G04',
  'sildenafilo': 'G04',
  'sildenafilo equivalentes sildenafilo': 'G04',
  'sildenafilo mgequivalentes sildenafilo': 'G04',
  'sildenafilo sildenafilo': 'G04',
  'sildenafilobase': 'G04',
  'silice coloidal anhydro': 'C09',
  'silimarina': 'A05',
  'silimarina eqivalente silimarina': 'A05',
  'silodosina': 'G04',
  'simeticona': 'A03',
  'simeticona al': 'A02',
  'simeticona emulsion': 'A02',
  'simeticona emulsionada equivalnete dimetilpolisiloxano': 'A03',
  'simeticona equivalentes dimeticona': 'A03',
  'simeticona granulos': 'A02',
  'simeticona polvo': 'A03',
  'simeticona polvo al *': 'A03',
  'simeticona simeticona equivalen adimeticona': 'A03',
  'simeticona va cubierta': 'A09',
  'simvastatina': 'C10',
  'simvastatina*': 'C10',
  'singapore gp cepa analoga': 'J07',
  'singapur gp cepa analoga': 'J07',
  'sirolimus': 'L04',
  'sitaglipina': 'A10',
  'sitagliptina': 'A10',
  'sitaglitina': 'A10',
  'smectita dioctahedral': 'A07',
  'sodiodihidratado': 'A07',
  'sofosbuvir': 'J05',
  'solifenacina': 'G04',
  'solifenacinasuccinato': 'G04',
  'solucion al': 'B05',
  'solucion alquitran hulla': 'V08',
  'solucion aminoacidos alanina arginina glicina histidina isoleucina leucina lisina metionina fenilalanina prolina serina taurina treonina triptofano tirosina valina': 'B05',
  'solucion cianocobalamina': 'A11',
  'solucion contiene clorhexidina digluconato solucion al': 'D08',
  'solucion contienen isoleucina': 'B05',
  'solucion esteril hidroxipropilmetilcelulosa al equivalentes hidroxipropilmetilcelulosa': 'S01',
  'solucion partida galio': 'V09',
  'solucion piridoxina': 'A11',
  'solucion tiamina': 'A11',
  'somatrogon': 'H01',
  'somatropina': 'H01',
  'somatropina recombinante': 'H01',
  'sorafenib': 'L01',
  'streptococcus pneumoniae tipo': 'J07',
  'streptococcus pneumoniae tipo b': 'J07',
  'streptococcus pneumoniae tipo c': 'J07',
  'streptococcus pneumoniae tipo f': 'J07',
  'streptococcus pneumoniae tipo n': 'J07',
  'streptococcus pneumoniae tipo v': 'J07',
  'streptococcus salivarius subesp thermophilus minimo': 'G01',
  'streptococcus salivarius subsp thermophilus minimo': 'G01',
  'subacetato aluminio': 'C05',
  'subsalicilato bismuto': 'A02',
  'succimero': 'V09',
  'succinatodedoxilamina': 'N02',
  'succinilcolina cloruro': 'M03',
  'sucralfato': 'A02',
  'sucralfato no': 'A02',
  'sucralfatomicronizado': 'A02',
  'sucralosa': 'B05',
  'sugammadex': 'V03',
  'sugammadex sugammadex': 'V03',
  'sulbactam': 'J01',
  'sulbactan': 'J01',
  'sulbutiamina': 'A11',
  'sulfacetamida': 'S01',
  'sulfadiazina': 'J01',
  'sulfadiazina plata': 'D06',
  'sulfadoxina': 'P01',
  'sulfametizol': 'J01',
  'sulfametoxazol': 'J01',
  'sulfasalazina': 'A07',
  'sultamicilina': 'J01',
  'sultamicilina *': 'J01',
  'sultamicilina tosilato': 'J01',
  'sumatriptan': 'N02',
  'sumatriptan ep': 'N02',
  'sumatriptan equivalentes sumatriptan': 'N02',
  'sunitinib': 'L01',
  'sunitinib capsulas duras': 'L01',
  'sunitinib equivalentes sunitinib': 'L01',
  'sunitinib malato': 'L01',
  'sunitinib malato sunitinib': 'L01',
  'surfactante asociado con las proteinas b c': 'R07',
  't butil metoxidibenzoilmetano': 'D11',
  'tacrolimus': 'L04',
  'tadafilo': 'G04',
  'tadalafil': 'G04',
  'tadalafilo': 'G04',
  'tadalafilomicronizado': 'G04',
  'tafamidis': 'N07',
  'tak mr equivalentes dexlansoprazol': 'A02',
  'talazoparib': 'L01',
  'talco purificado': 'C09',
  'talcopurificado': 'C09',
  'talidomida': 'L04',
  'tamoxifeno': 'L02',
  'tamsulosina': 'G04',
  'tamsulosina pellets equivalentes tamsulosina al': 'G04',
  'tamsulosina seca': 'G04',
  'tamsulosinaclorhidrato': 'G04',
  'tapentadol': 'N02',
  'tapentadol equivalentes tapentadol': 'N02',
  'taurina': 'B05',
  'tavoprost': 'S01',
  'tazaroteno': 'D05',
  'tazobactam': 'J01',
  'tazobactam gramos equivalentes tazobactam': 'J01',
  'tecnecio metaestable pertecnetato fecha calibracion': 'V09',
  'tecnecio metaestable pertecnetato gbq fecha referencia': 'V09',
  'tecnecio pertecnectato': 'V09',
  'teduglutida': 'A16',
  'tegoprazan': 'A02',
  'teicoplanina': 'J01',
  'telipresina': 'H01',
  'telmisartan': 'C09',
  'temozolamida': 'L01',
  'temozolomida': 'L01',
  'tenecteplasa': 'B01',
  'tenofovir alafenamida': 'J05',
  'tenofovir alafenamida equivalentes atenofovir alafenamida': 'J05',
  'tenofovir alafenamida monofumarato equivalentes tenofovir alafenamida': 'J05',
  'tenofovir alafenamida tenofovir alafenamida': 'J05',
  'tenofovir disopoxilo': 'J05',
  'tenofovir disoproxil': 'J05',
  'tenofovir disoproxil fuamarato': 'J05',
  'tenofovir disoproxil fumarate': 'J05',
  'tenofovirdisoproxil': 'J05',
  'teofilina': 'R03',
  'teofilinaanhidra': 'R03',
  'teprotumumab': 'L04',
  'terazosin': 'G04',
  'terazosina': 'G04',
  'terbinafiba': 'D01',
  'terbinafina': 'D01',
  'terbinafina equivalentes terbinafina': 'D01',
  'terbinafinabase': 'D01',
  'terbutalina': 'R03',
  'terconazol': 'G01',
  'teriflunomida': 'L04',
  'teriparatida': 'H05',
  'terlipresina correspondiente terlipresina': 'H01',
  'testosterona': 'G03',
  'testosterona enantato': 'G03',
  'testosterona undecanoato': 'G03',
  'tetra': 'V09',
  'tetrabenazina': 'N07',
  'tetraborato decahidrato': 'A12',
  'tetracaina': 'S01',
  'tetraciclina': 'A01',
  'tetrafluoroborato [tetrakis cobre ]': 'V09',
  'tetrafluoroborato tetramibi cobre': 'V09',
  'tetrafosmina': 'V09',
  'tetrahidrozolina': 'S01',
  'tetrakis cobre tetrafluoroborato cu': 'V09',
  'tetrosfosmina tetrafluoroborato': 'V09',
  'tezepelumab': 'R03',
  'thimerosal': 'D08',
  'thiotepay se realizara dilucion con agua para inyeccion para quedar una concentracion post dilucion': 'L01',
  'tiamina': 'A11',
  'tiamina monohirato': 'A11',
  'tiamina mononitrato': 'A11',
  'tiaminaclorhidrato': 'A11',
  'tiaminamononitrato': 'A11',
  'tibolona': 'G03',
  'ticagrelor': 'B01',
  'tigeciclina': 'J01',
  'timolol': 'S01',
  'timolol equivalentea timolol': 'S01',
  'timolol equivalentes timolol': 'S01',
  'timolol timolol': 'S01',
  'tinidazol': 'P01',
  'tiocolchicosido': 'M03',
  'tioguanina': 'L01',
  'tiomersal': 'D08',
  'tiopental': 'N01',
  'tiosulfato': 'V03',
  'tiotepa': 'L01',
  'tiotropio': 'R03',
  'tiotropio mgequivalente tiotropio': 'R03',
  'tipiracilo': 'L01',
  'tirofiban': 'B01',
  'tirosina': 'B05',
  'tirotropina alfa': 'H01',
  'tirzepatida': 'A10',
  'tizanidina': 'M03',
  'tizanidina equivalentea tizanidina': 'N02',
  'tizanidina equvalente tizanidina': 'N02',
  'tizanidina seca': 'M03',
  'tizanidinabase': 'M03',
  'tobramicina': 'S01',
  'tobramicina tobramicina': 'S01',
  'tocilizumab': 'L04',
  'tofacitinib': 'L04',
  'tofacitinib equivalentes tofacitinib': 'L04',
  'tolnaftato': 'D07',
  'tolterodina': 'G04',
  'topiramato': 'N03',
  'topotecan': 'L01',
  'tosilato niraparib': 'L01',
  'toxina botulinica tipo': 'M03',
  'toxina botulinica tipo clostridium botulinum': 'M03',
  'toxina botulinica tipo libre proteinas complejantes dl': 'M03',
  'toxina botulinica tipo purificada clostridium botulinum': 'M03',
  'toxina botulinica tipo purificada clostridium botulinum cepa hall': 'M03',
  'toxina clortridium botulinum tipo': 'M03',
  'toxina clostridium botulinum tipo': 'M03',
  'toxina tipo': 'M03',
  'toxoide difteria modificado lf': 'J07',
  'toxoide difterico': 'J07',
  'toxoide difterico adsorbido': 'J07',
  'toxoide diftericono menos': 'J07',
  'toxoide pertusico adsorbido': 'J07',
  'toxoide pertusico purificado absorbido': 'J07',
  'toxoide pertussis': 'J07',
  'toxoide purificado adsorbido pertussis': 'J07',
  'toxoide purificado difteria lf': 'J07',
  'toxoide purificado tetano lf': 'J07',
  'toxoide tetanico': 'J07',
  'toxoide tetanico adsorbido': 'J07',
  'toxoide tetanico purificado lf': 'J07',
  'toxoide tetanicono menosde': 'J07',
  'toxoide tetanicopurificado concentrado no menos': 'J07',
  'toxoidedifterico': 'J07',
  'trabectedina': 'L01',
  'tracolimus': 'L04',
  'tramadol': 'N02',
  'tramadol hcl': 'N02',
  'tramadolclorhidrato': 'N02',
  'trametinib dimetilsulfoxido': 'L01',
  'trandolapril': 'C09',
  'trastuzumab': 'L01',
  'trastuzumab deruxtecan': 'L01',
  'trastuzumab emtansina': 'L01',
  'travoprost': 'S01',
  'trazodona': 'N06',
  'tremelimumab': 'L01',
  'treonina': 'B05',
  'treprostimil': 'B01',
  'treprostinil': 'B01',
  'tretinoina': 'D11',
  'triamcinolona acetonido': 'H02',
  'triancinolona acetonido': 'A01',
  'triazolam': 'N05',
  'tribenosido': 'N01',
  'triclosan': 'D08',
  'trientina': 'A16',
  'trientina clorhidarto': 'A16',
  'trietil': 'C09',
  'trifluoperazina': 'N05',
  'trifluridina': 'L01',
  'trigliceridos acidos grasos saturados cadena media': 'B05',
  'trigliceridos cadena media': 'B05',
  'trigliceridos cadena media mct': 'B05',
  'trigliceridos cadena mediana': 'B05',
  'trigliceridos con acidos grasos omega acido alfa linolenico acido eicosapentanoico acido docosahexanoico': 'B05',
  'trihidratado': 'B05',
  'trimebutina': 'A03',
  'trimebutinamaleato': 'A03',
  'trimetazidina': 'C01',
  'trimetazidinadiclorhidrato': 'C01',
  'trimetil tetradecil amonio': 'D08',
  'trimetoprim': 'J01',
  'trimetoprim trimetoprim': 'J01',
  'trimetoprima': 'J01',
  'trimetropima': 'J01',
  'trimetropin': 'J01',
  'trimetroprima': 'J01',
  'trioxido arsenico': 'L01',
  'triptofano': 'B05',
  'triptorelina': 'L02',
  'triptorelina triptorelina': 'L02',
  'trisodico': 'A07',
  'trombina': 'B02',
  'trombina humana': 'B02',
  'tropicamida': 'S01',
  'tuberculina': 'V04',
  'turoctocog alfa pegol': 'B02',
  'ulipristal': 'G03',
  'umeclidinio': 'R03',
  'umeclidinio equivalentea umeclidinio': 'R03',
  'una liberada formoterol dihidratado': 'R03',
  'una liberada glicopirronio': 'R03',
  'una libreada beclometasona': 'R03',
  'una recubiertaen interior blandaconacido fenofibrico': 'C10',
  'undecanoato testosterona': 'G03',
  'undecilenato zinc': 'D01',
  'unidades fip actividad lipasa unidades fip actividad amilasa unidades fip actividad proteasa': 'A09',
  'unidades ph eur lipasa unidades ph eur amilasa unidades ph eur proteasa': 'A09',
  'upadacitinib': 'L04',
  'urapidil': 'C02',
  'urea': 'D02',
  'urea c': 'V04',
  'ustekinumab': 'L04',
  'valaciclovir': 'J05',
  'valaciclovir hidrato valaciclovir': 'J05',
  'valganciclovir': 'J05',
  'valganciclovir equivalentes valganciclovir': 'J05',
  'valina': 'B05',
  'valproato': 'N03',
  'valproato acido valproico equivalentes valproato': 'N03',
  'valsartan': 'C09',
  'valsartan disodico': 'C09',
  'vanacomicina': 'J01',
  'vancomicina': 'J01',
  'vancomicina vancomicina': 'J01',
  'vancomina': 'J01',
  'vancomiocina': 'J01',
  'vardenafil': 'G04',
  'vaselina blanca': 'N01',
  'vasopresina': 'H01',
  'vecuronio': 'M03',
  'vecuroniobromuro': 'M03',
  'vedolizumab': 'L04',
  'velaglucerasa alfa': 'A16',
  'velmanasa alfa': 'A16',
  'velpatasvir': 'J05',
  'vemurafenib': 'L01',
  'venetoclax': 'L01',
  'venlafaxina': 'N06',
  'venlafaxina sr pellets': 'N06',
  'venlafaxina venlafaxina': 'N06',
  'verapamilo': 'C08',
  'verapamiloclorhidrato': 'C09',
  'verde indocianina': 'V04',
  'vericiguat': 'C01',
  'vesiculas purificadas membrana externa meningococo serogrupo b': 'J07',
  'vidagliptina': 'A10',
  'vigabatrina': 'N03',
  'vilanterol': 'R03',
  'vildagliptina': 'A10',
  'vildagliptina comprimidos': 'A10',
  'vinblastina': 'L01',
  'vincristina': 'L01',
  'vinorelbina': 'L01',
  'virus contra rabia producido lineas celulas vero einactivado con beta propiolactona > * potencia medida utilizando prueba nih antes despues decalentamiento c durante un mes': 'J07',
  'virus fiebre amarilla cepa d ab no menos': 'J07',
  'virus hepatitis': 'J07',
  'virus hepatitis inactivado': 'J07',
  'virus hepatitis purificado inactivado': 'J07',
  'virus inactivado hepatitis cepa gmb cultivada celulas diploides humanas mrc': 'J07',
  'virus poliomielitis inactivado tipo': 'J07',
  'virus poliomielitis inactivados tipo': 'J07',
  'virus vivo atenuado varicela cepa oka merck ufc': 'J07',
  'virus vivos atenuado paperas cepa jeryl lynn': 'J07',
  'virus vivos atenuados parotiditis cepa jeryl lynn': 'J07',
  'virus vivos atenuados parotiditis mayor igual ^': 'J07',
  'virus vivos atenuados rubeola cepa wistar ra': 'J07',
  'virus vivos atenuados rubeola mayor iigual ^': 'J07',
  'virus vivos atenuados rubeolade cepa wistar ra': 'J07',
  'virus vivos atenuados sarampion derivada cepa edmonson b': 'J07',
  'virus vivos atenuados sarampion derivados cepa edmonston b': 'J07',
  'virus vivos atenuados sarampion mayor iigual ^': 'J07',
  'virus vivos atenuados varicela cepa oka merck': 'J07',
  'virusde polio inactivado tipo': 'J07',
  'vismodegib': 'L01',
  'vitamin': 'A11',
  'vitamin capsulas blandas': 'A11',
  'vitamin k': 'B05',
  'vitamina': 'A11',
  'vitamina acomo': 'A11',
  'vitamina b': 'A11',
  'vitamina b equivalentes vitamina b': 'A11',
  'vitamina b pura': 'A11',
  'vitamina c': 'A11',
  'vitamina c total acido ascorbico': 'A11',
  'vitamina d': 'A11',
  'vitamina d equivalentea': 'A12',
  'vitamina d equivalentes vitamina d': 'A11',
  'vitamina d seca tipo sd s': 'A11',
  'vitamina d seca tipop cws': 'A11',
  'vitamina dl alfa tocoferyl vitamina sintetica': 'A11',
  'vitamina equivalentes vitamina': 'A11',
  'vitamina k': 'B02',
  'vitamina sintetica': 'V04',
  'vitaminaa': 'A11',
  'vitaminac': 'A11',
  'vitaminad equivalentes vitamina d': 'A11',
  'vitaminak': 'B02',
  'voretigen neparvovec concentrado para solucion inyec': 'S01',
  'voriconazol': 'J02',
  'voriconazole': 'J02',
  'vortioxetina': 'N06',
  'vortioxetina vortioxetina': 'N06',
  'vortioxetinabase': 'N06',
  'vortioxina': 'N06',
  'warfarina': 'B01',
  'warfarina clatrate equivalentes warfarina': 'B01',
  'yodo': 'V08',
  'yodo activo *': 'D08',
  'yodo disponible': 'D08',
  'yodo metalico resublimado': 'D02',
  'yodo polivinilpirrolidona': 'D08',
  'yodo polivinilpirrolidona equivalenteiodo activo': 'R02',
  'yodopovidona': 'D08',
  'yodopovidona polvo': 'D08',
  'yodopovidona*': 'R02',
  'yoduro': 'A11',
  'yoduro mbq': 'V09',
  'yoduro mbq fecha calibracion': 'V10',
  'yoduro mcgequvalente yodo': 'A11',
  'yoduro na i desde mbq hasta': 'V10',
  'zanubrutinib': 'L01',
  'zidovudina': 'J05',
  'zinc': 'A12',
  'zinc dihidratado': 'B05',
  'zinc equivalentes zinc': 'A12',
  'zinc heptahidratado': 'B05',
  'zinc monohidratado': 'A11',
  'zinc*': 'A07',
  'zitromicina': 'J01',
  'zofenopril': 'C09',
  'zolpidem hemitartrato': 'N05',
  'zopiclona': 'N05',
  'zoplicona': 'N05',
})
